### ISSUE TITLE
Input - Mouse: Add support for right & middle mouse buttons

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#1]
All mouse clicks are currently interpreted as left mouse clicks - updating the app to recognize middle / right would be helpful.

**Comment by extr0py** [comment]
Also need to look at handling modifir keys - control, alt, shift

**Comment by bert88sta** [comment]
@extr0py I'm kind of an idiot to JS/TS, but if you could point me to some resources that would help me specifically understand the overview of the events and how they interact with the neovim instance (besides me combing the source) I could probably get some of these easier ones done :)

**Comment by bert88sta** [comment]
Just to get started, is the UI going to hijack the right/middle click? It seems like neovim uses them for little to nothing, and most people's terminals already intercept them.

**Comment by extr0py** [comment]
@bert88sta - thanks for the PR for scrolling! Sorry that I was slow to reply to this thread. Looks like you have a pretty good grasp on the mouse events in Input/Mouse.ts, so that's great - that and Input/Keyboard.ts is where most of the action is. 

The Mozilla docs are a really good reference for the general mouse events: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent
but seems like you already got the info on the scroll / delta to implement it.

Regarding middle/right click, I think you're right, it should be safe to intercept them. I don't remember ever using right/middle click with GVIM. Right-click might be nice to show a context menu at some point, but the scrolling is the most important functionality at the moment - thanks again for implementing it!

**Comment by extr0py** [comment]
I'll close this since the most important case is addressed with #45, but if there is other mouse related functionality you'd like to explore we can open a new issue or re-open this.
