### ISSUE TITLE
PageUp/PageDown don't work on Linux

### ISSUE THREAD

**Issue by cjb** [extr0py/oni#112]
Thanks for oni!

Pressing Page Up/Page Down just inserts the string "PageUp" or "PageDown" into my documents on Linux.  (Also, while scrolling with the mouse wheel, looks like the bottom line of the display gets corrupted/overwritten, see below.)

Otherwise looks to be working well on Linux!

![screenshot from 2016-12-19 14-27-21](https://cloud.githubusercontent.com/assets/21217/21326121/538b5418-c5f7-11e6-8a37-9b3176b8a14e.png)

**Comment by extr0py** [comment]
Cheers @cjb ! Looks great. It was previously much uglier on Linux before @JakubJecminek fixed the fonts. :)

The <PageUp>/<PageDown> issue should be fixed, and I have a PR to fix the bottom line issue out now. I'll publish a new NPM package today too with those fixes.

Thanks for trying it out and reporting those issues!

**Comment by extr0py** [comment]
Just pushed 0.1.5 to NPM - should be fixed now.
