### ISSUE TITLE
Init.vim sourcing doesn't include colorscheme

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#118]
Is this intentional?

I have to source init.vim after loading (Mine is set to load init.vim automagically) to get the color scheme I like

**Comment by extr0py** [comment]
Hi @bert88sta ,

Do you have these options set in the config.json?

```
"oni.loadInitVim": true,
"oni.useDefaultConfig": false
```

Right now, even if the init.vim is loaded, the default config is loaded after, and that sets the `onedark` colorscheme. It's a little confusing at the moment that both these properties have to be set. Does it work with those settings?

**Comment by bert88sta** [comment]
You're right, this can be closed. We've got to find a way to conditionally load the most important priority config items first, i.e. load init.vim and default any conflicts to init.vim

**Comment by extr0py** [comment]
Makes sense, maybe long-term we could set it up to source the init.vim after the defaults are set (so they are overridden by the init.vim). I'll close it for now though but let me know if you have any ideas. Thanks!

**Comment by MikaAK** [comment]
I'm having an issue where I do have these settings but it's still not respecting my colorscheme!

**Comment by extr0py** [comment]
@MikaAK - weird! Would you mind sharing your `config.js` as well as a screenshot of Oni?

In addition, which version / platform are you running?

**Comment by MikaAK** [comment]
![image](https://user-images.githubusercontent.com/4650931/30461134-b2bc5a0c-9970-11e7-98a8-e718d2d82f5a.png)

```javascript
const activate = (oni) => {
   console.log("config activated", oni)

   oni.input.unbind("<Tab>")
   oni.input.unbind("<c-p>")

   oni.input.bind("<Tab>", "completion.next")
   oni.input.bind("<S-Tab>", "completion.previous")
   oni.input.bind("<CR>", "completion.complete")
}

const deactivate = () => {
   console.log("config deactivated")
}

module.exports = {
  activate,
  deactivate,
  "oni.loadInitVim": true,
  "oni.useDefaultConfig": false,
  "editor.fontFamily": "Hack"
}
```

I'm on rc4 / osx and in my `init.vim` I do have `colorscheme molokai` enabled
