### ISSUE TITLE
Delay appearance of QuickInfo

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#120]
If I'm navigating a file (moving the cursor around) I don't need the QuickInfo to appear.  Oni should only show the QuickInfo if my cursor stops moving for maybe 500ms or so.  Otherwise, the QuickInfo is distracting.

![quickinfo](https://cloud.githubusercontent.com/assets/817509/21460023/1bc912ce-c901-11e6-8e81-6e2bef66ccaa.gif)

**Comment by extr0py** [comment]
Makes sense, this can be pretty noisy, thanks for the suggestion

One alternative I was thinking of as well was to have a command to toggle QuickInfo on/off - would that be helpful here? The 500ms delay sounds pretty good too - sort of like the CursorHold event in VIM.

There's also the setting `editor.quickInfo.enabled`, to disable it completely, but it's not very discoverable at the moment.

**Comment by keforbes** [comment]
I don't want to disable QuickInfo, it's very useful *when I'm interested in it*.  The problem is just that if I'm running my cursor over things I don't care to see details of the things I'm flying past.  It's only when my cursor stops that I'm interested in the nearby context.

**Comment by keforbes** [comment]
Also, I think changing this could improve some responsiveness in the UI.  If we buffer the event and only send the request when the cursor stops moving then we aren't calling the "go fetch quick info" method with every key press (repeated or otherwise).

I was playing with a prototype where I buffered the event so it only displayed after a 500ms pause but this led to the quickinfo remaining visible an additional 500ms when it should've disappeared.  So this would probably require a more architectural change which is above my pay-grade. :smile:

**Comment by extr0py** [comment]
Just merged in a change for this - #128 . Give it a try and let me know if there any issues.

**Comment by keforbes** [comment]
I finally got a chance to test this out.  Works great, thanks!
