### ISSUE TITLE
Does not currently support ligatures

### ISSUE THREAD

**Issue by kybaeus** [extr0py/oni#138]
Oni does not currently support ligatures such as those used in [Fira Code](https://github.com/tonsky/FiraCode). As inconsequential as it may sound, this is one of the primary reasons keeping me tied to Atom.

Unfortunately, due to limitations in the 2d Canvas context api, it does not seem possible to add ligatures using CSS-only methods such as [this](https://github.com/zeit/hyper/issues/914).

**Comment by extr0py** [comment]
Thanks for the report! This is interesting, I haven't used fonts that support ligature for development. I'm trying out Fira Code now.

One investigation I have ongoing is looking at using  a DOM-based rendering strategy (as opposed to Canvas). I believe this could potentially be more performant, and could potentially solve this problem. It potentially would also help with #126 as well

**Comment by extr0py** [comment]
I started looking at a DOM strategy, and it looks promising (PR #140). The ligatures are rendering correctly:
![image](https://cloud.githubusercontent.com/assets/13532591/21597543/08836644-d101-11e6-88f4-e9c0849995f4.png)

Some bugs

**Comment by extr0py** [comment]
Fixed by #140, which switches to a DOM rendering strategy (so ligature comes free with that) - I'm enjoying ligatures via Fira Code now :)

Let me know if you still see any issues!
