### ISSUE TITLE
how to install on windows?

### ISSUE THREAD

**Issue by dengxqi** [extr0py/oni#141]
can anybody tell me how to run oni on windows? does it need special gui plugin? i run the nvim.exe in folder `bin/x86/Neovim/bin`, but it just give me a messege like follows. thanks.

```
Neovim was built without a Terminal UI,press Ctrl+C to exit
currently listening on the following address(es)
        \\.\pipe\nvim-37972-0
```

**Comment by gaving** [comment]
you shouldn't need to do anything special, `npm install -g oni` then just run the `oni` command and that should take care of the nvim spawning for you

**Comment by extr0py** [comment]
Will close this since it was addressed - thanks @gaving ! @dengxqi , feel free to reopen this to continue the discussion if it is still not opening for you.
