### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by sharksforarms** [extr0py/oni#142]
https://zippy.gfycat.com/InfamousHappygoluckyFlyingsquirrel.webm

Fresh install of Fedora 25
- Installed neovim
- Installed oni
- When run on command line, nothing happens, program quits
- Cloned/Built oni
- When run on command line, nothing happens, program quits

Am I doing something wrong?

**Comment by extr0py** [comment]
Hi @sharksforarms - can you please detail the exact commands you used for installing & cloning & building? 

In your built directory, you want to make sure that you have run - `npm link`, and you'll want to remove the global reference if it exists from the install step, so you'd want to run these commands from the cloned directory:
`npm rm -g oni-vim`
`npm link`

(You may have to prefix with `sudo` depending on your folder permission structure)

**Comment by sharksforarms** [comment]
`
https://github.com/extr0py/oni.git
cd oni/
sudo npm install
sudo npm run build
sudo npm link
oni
`

I have tried running your suggested commands to no avail, it still doesn't start

**Comment by extr0py** [comment]
Interesting, sorry there are still problems. I haven't tested on Fedora 25, my Linux machine is on Ubuntu, which seems to work.

One thing you can try, to rule out an `npm link` issue, is:
```
cd oni
node cli/oni
```

If that works, than it means that there is a problem with the way NPM linked to this file.

if that does not work, then there's something else going on (maybe a node version issue? Would be helpful to know the node / npm version in this case). You could also try adding some debug logging in cli/oni via `console.log(...)` to see if it is crashing at a particular point.

**Comment by sharksforarms** [comment]
Added some console.log() to see the actually command being run:
`[sharks@localhost oni]$ /home/sharks/oni/node_modules/.bin/electron /home/sharks/oni/main.js
/home/sharks/oni/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
`

`sudo dnf whatprovides libXss.so.1
...
libXScrnSaver...
...
`

After installing libXScrnSaver, oni now starts up.

**Comment by extr0py** [comment]
Thanks for the update, @sharksforarms ! Glad it is working now. Feel free to submit a PR if there are some additions we should make to the installation instructrion to make this easier in the future.
