### ISSUE TITLE
Oni process doesn't go to background at start

### ISSUE THREAD

**Issue by xangelux** [extr0py/oni#146]
Version 0.1.6 (the one installed by NPM).
Issue: When oni is started, it doesn't release the console to the prompt
expected behavior: being able to use the terminal window after starting Oni
Additional info: When started from terminal, if the terminal is closed, Oni is closed with it

**Comment by extr0py** [comment]
👍 👍 

Thanks for logging this, @xangelux ! Agreed, this is annoying, would be nice to have a fix for it. If anyone is up for looking at this, it's definitely a problem with the way we are starting the process in `cli\oni`. 

This is some good info: http://stackoverflow.com/questions/12871740/how-to-detach-a-spawned-child-process-in-a-node-js-script

A few things we likely need to do here:
1) Set the `detached` flag to true
2) Stop piping stdin/stdout/stderr

**Comment by Rafi993** [comment]
[This](https://github.com/electron/electron/issues/2208) seemed promising

**Comment by Rafi993** [comment]
I gave a small[ pull request ](https://github.com/extr0py/oni/pull/150)as given there hope it solves the issue

**Comment by extr0py** [comment]
Thanks @Rafi993 ! Works great on Linux. There is still a problem in Windows - it does immediately exit the terminal process, but it also spins up a separate Node console. I'll open a separate PR to address the windows issue.

**Comment by city41** [comment]
I am on Ubuntu 17.10 using bash and I still find Oni needs to be remained attached to the shell. If I launch with `oni .`, then it doesn't seem to detach. If I ctrl-c in the terminal, Oni quits. If I launch with `oni . &`, Oni never quite comes up right. I can only get it working if I then `fg`, which then has the net result as just launching with `oni .`.

I just installed Oni this morning, it is version 0.3.1 according to the about box.

**Comment by SamHH** [comment]
I experience this issue on Arch with the Alacritty terminal, but not on macOS with iTerm2.
