### ISSUE TITLE
Background-image is null by default

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#156]
If you look at the Developer Tools in Oni, you'll see an error at startup:
```
GET file:///<path>/oni/null net::ERR_FILE_NOT_FOUND
```

This is because the background-image is defaulting to null
```
<div class="background-image" style="background-image: url("null"); background-size: cover;"></div>
```

The image is defined here
```
const backgroundImageUrl = Config.getValue<string>("prototype.editor.backgroundImageUrl")
backgroundImageElement.style.backgroundImage = "url(" + backgroundImageUrl + ")"
```

So it looks like `prototype.editor.backgroundImageUrl` isn't defined by default.  I'm filing this as a defect because I'm not sure what we want to do in the default case.

**Comment by keforbes** [comment]
https://subtlepatterns.com/tag/dark/  😄

**Comment by keforbes** [comment]
A couple examples taken from images in my link above:

![background_test_1](https://cloud.githubusercontent.com/assets/817509/21945958/72002c04-d99b-11e6-9ea5-3f4d3f09a81b.png)

![background_2](https://cloud.githubusercontent.com/assets/817509/21945959/7486b68c-d99b-11e6-9516-58ad4c9d9323.png)

Let me know if you want me to commit either of these.

**Comment by extr0py** [comment]
Just saw your PR - thanks for the suggestions! Will be nice to showcase this feature :)
