### ISSUE TITLE
init.vim not sourced

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#16]
Currently, the default init.vim is overwritten, to set the runtimepaths to pick up the plugins that are needed for Oni to function correctly.

However, this means settings aren't pulled in for custom init.vim

Need to source the user's init.vim, if it exists, once the app has started. Seems like we might want to add this in (NeovimInstance.ts)[https://github.com/extr0py/oni/blob/master/browser/src/NeovimInstance.ts] once the process has been spawned, we can source the init.vim if it exists.

**Comment by darkwater** [comment]
Couldn't the extra runtimepaths be added through a command line option? `--cmd <command>` is executed before processing any vimrc, so this looks like a good way to set rtp.

**Comment by darkwater** [comment]
Applying http://novaember.com/s/8f9453/ig79Ko.txt will append ONI's runtimepaths to the standard, but I haven't tested for any side-effects. (And of course the code is ugly because I just changed some things to make it work.)

 I also noticed a rather long startup time, not sure what that's caused by.

**Comment by extr0py** [comment]
Thanks for the code snippet! I ported it over to a PR - #18. That's a great suggestion, I didn't know about the --cmd option, would be more robust than dynamically generating the init.vim.

I'm seeing a problem too though with the PR - it looks like Neovim is hitting an error that isn't getting rendered, so you need a keypress to activate the UI. (This might explain the long startup time in your case, too). Unfortunately, I'm not sure what that error is, so need to dig in a little more and see what's happening before bringing that PR in. Sometimes, if there's a script error on load, it doesn't make it to the UI - seems related to this issue in Neovim core: https://github.com/neovim/neovim/issues/3901

**Comment by extr0py** [comment]
I believe this should be fixed by PR #18 - try out the `oni.useDefaultConfig` option and let me know.

Thanks!
