### ISSUE TITLE
issue with launching v0.1.7

### ISSUE THREAD

**Issue by rockneverdies55** [extr0py/oni#167]
Just installed oni-vim@0.1.7 using `npm install -g oni-vim` command on windows.

When I ran `oni` in the command line, I got this:

![image](https://cloud.githubusercontent.com/assets/4588562/22026390/a6f800a2-dc9e-11e6-872b-63d6f56695d4.png)

I see 0.1.7.2 in the releases tab, if the package on npm repos isn't the latest please update it.

**Comment by extr0py** [comment]
Thanks for the report, @rockneverdies55 !

What version of `node` do you have? You can check by running `node --version` at the command prompt.

I'll have a fix for this shortly - I believe some of the ES6 constructs we are using in the script may not be supported by older node versions.

**Comment by extr0py** [comment]
Pushed a fix to master, will bump the release as well

**Comment by extr0py** [comment]
Resolved by this change: https://github.com/extr0py/oni/commit/356cff48e26a4b4b0bf1ad8fa1dc4c7bcf42dc52

**Comment by rockneverdies55** [comment]
Confirming the fix with 0.1.8. Thanks.
