### ISSUE TITLE
Icon reverted back to Electron icon

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#168]
I updated my cloned repo to the current state (v0.1.8.1) and the application icon reverted back to the default electron icon.

I'm on Linux if that matters.  Let me know if I'm the only one seeing this.

**Comment by extr0py** [comment]
Just tested this for me (on latest master)

Windows:

![image](https://cloud.githubusercontent.com/assets/13532591/22064716/8f39ade4-dd39-11e6-8ae2-60f957cfe25e.png)

**Comment by extr0py** [comment]
And Ubuntu Linux:
![image](https://cloud.githubusercontent.com/assets/13532591/22064753/cb160754-dd39-11e6-9aa4-84ad64557281.png)

**Comment by extr0py** [comment]
So looks like mine is working okay - but there could've been some change that impacted this on another environment.

Couple things to try:
1) If you revert back to the v0.1.6.1 release (https://github.com/extr0py/oni/releases/tag/v0.1.6.1), does the application icon start working again? That would indicate there was a change between then and v0.1.8 that broke something.
2) You could try running `npm rm -g oni-vim` and `npm link` from the project directory

It's possible that one of these PRs - #150 or #152 impacted this, so it might be worth reverting / tweaking those specifically to see if they are the culprits

**Comment by keforbes** [comment]
I reverted to v0.1.6.1 and it was still missing the icon so I must've broken something in my local environment.  I'll close this issue.
