### ISSUE TITLE
Ligature: When cursor is over a ligature, show underlying character

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#172]
![ligature](https://cloud.githubusercontent.com/assets/13532591/22066632/acc328aa-dd42-11e6-96ec-0129479773f6.gif)

For a scenario like above, where the cursor moves across the ligature (!==), it would be nice to see the underlying character, especially if someone is not familiar with ligatures.

This wouldn't need to be special cased for ligatures - we could always show the underlying character in the cursor when the cursor is on top of an item.

**Comment by topaxi** [comment]
Is there a way to disable this behavior?

**Comment by bryphe** [comment]
@topaxi - currently there isn't a way to change this behavior. When we render the cursor, we render the character in isolation (inverted), so it doesn't have context about the ligature. It's solvable (we could potentially be smarter about how we render that), but not currently implemented. Feel free to log an issue if it's something you'd like to see!

**Comment by topaxi** [comment]
Doesn't bother me much, it was a bit "wobbly" in the beginning, I'll open an issue if it bothers me after some more oni usage! :)

**Comment by bryphe** [comment]
Sounds great, thanks @topaxi !

FYI, you can disable the cursor 'bounce' animation by setting `ui.animations.enabled` to false if it is distracting.
