### ISSUE TITLE
Why is oni scanning my ~/.Trash ?

### ISSUE THREAD

**Issue by jordwalke** [extr0py/oni#177]
When I started oni and used the command pallet (command shift p), it gave me a message:

```
Error: Error: ENOENT: no such file or directory, stat '/Users/me/.Trash/SomeFile 5.09.00 PM'
```

Why is it scanning the trash in the first place when opening the command pallet? I think it should have a blacklist of directories perhaps. Or maybe this should be included in wildignore and oni should ignore it?

**Comment by extr0py** [comment]
Seems like it might be related to #125 (at least, the error message).

Right now,  in a non-git folder, we recursively read all directories / files for the 'quick open' service. Having a blacklist sounds good - for example, VSCode has the `files.exclude` setting in its config, would make sense to have a similiar option. 

I like the idea of linking it to the whitelist property, too - seems like #20 might apply in terms of how we synchronize the VIM/JS configuration & keybindings.

Regarding the configuration, a reasonable set of defaults could be:
```
["**/.git", "**/.svn", "**/.hg", "**/.DS_Store", "**/.Trash"]
```

**Comment by keforbes** [comment]
I believe this defect can be closed now that #268 has been merged in.

**Comment by extr0py** [comment]
Thanks @keforbes ! I'll close this since the fix is in now. @jordwalke , feel free to reopen if you are still seeing issues.

**Comment by jordwalke** [comment]
Awesome!
