### ISSUE TITLE
How to debug?

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#178]
I see some reference to a debug/development mode in the build scripts but I can't figure out how to generate a sourcemap for bundle.js.  @extr0py, how do you debug oni?

**Comment by extr0py** [comment]
Good question @keforbes , I've been meaning to document this (and improve this).

I'm a sadist so I usually debug without sourcemaps.... But they are really helpful.

I started PR #180 to add the following:
- Documentation via CONTRIBUTING.md
- A `npm run build-debug` command that preserves sourcemaps
- Adding sourcemaps to `npm run start` (hot-reloading)

I hope that helps. Let me know if you have any feedback or other ideas to improve this. I want it to be easy to contribute!

**Comment by extr0py** [comment]
I'll close this out since i merged in #180 - but keep me posted if there are still issues getting sourcemaps.
