### ISSUE TITLE
Command Palette: Add documentation to README.md

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#185]
ONI also features a command palette, accessible via `<Control+Shift+P>`. This has a limited selection of items currently, but it does have a few useful items, especially for NPM. 

This should be showcased in the README along with documentation about the entry point.

**Comment by teto** [comment]
Related to palette you might be interested in https://github.com/neovim/neovim/pull/6288 (just need a US native to fix the descriptions with better English skills than I)

**Comment by extr0py** [comment]
Closing since this was fixed by @jasonszhao . Will look forward to picking up that Neovim change and including those commands in the Oni command palette :)
