### ISSUE TITLE
RFC 5686 in Neovim

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#187]
RFC 5686 from Neovim was merged in, so the question becomes:

What do we need to do to take advantage of the new features?

As someone who knows VimL better than JS (I don't know JS, so this is generous) I hope I can provide some sort of assistance.

EDIT: It's good to be back, I went AWOL there for a while.

**Comment by extr0py** [comment]
Good to have you back! I've unfortunately been AWOL this past week or so too - Feb is going to busy for me but I'm hoping can start to tackle some interesting stuff soon :)

Hopefully this will make it in soon! Will open up a lot of exciting scenarios for ONI
