### ISSUE TITLE
Just another quick colors problem.

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#188]
I use the terminal quite a bit in neovim, and having it match colors in Oni would be killer. 

I use zsh with agnoster theme and solarized dark color, but in Oni it looks like this:

![screen shot 2017-02-01 at 8 50 20 am](https://cloud.githubusercontent.com/assets/8421641/22509304/87840db0-e85b-11e6-837a-7f2ec124b852.png)

as opposed to this:

![screen shot 2017-02-01 at 8 51 15 am](https://cloud.githubusercontent.com/assets/8421641/22509325/9c60a41e-e85b-11e6-8b4e-e016912038df.png)

I know this probably isn't a high priority issue, but getting colors to be correct is a nice perk.

**Comment by extr0py** [comment]
Interesting. A couple of things to try would be to look at the DOM - with our new rendering strategy you can see all the elements and the colors associated with them:
![image](https://cloud.githubusercontent.com/assets/13532591/22510401/b1317f18-e846-11e6-8cf3-12a9dc69c003.png)

**Comment by extr0py** [comment]
And then the code that actually converts the colors is in `browser\src\action.ts` - the `colorToString` method:
![image](https://cloud.githubusercontent.com/assets/13532591/22510467/e28bbb50-e846-11e6-9fbb-cae48f6f07c0.png)

**Comment by justinmk** [comment]
This is a known limitation of `:terminal`. See `:h terminal-emulator-configuration`, the `{g,b}:terminal_color_*` variables define the 256-color `:terminal` palette, which could be set by oni programmatically, I suppose.
