### ISSUE TITLE
npm run install:oni-plugin-typescript fails

### ISSUE THREAD

**Issue by olleharstedt** [extr0py/oni#19]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'install:oni-plugin-typescript' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose config Skipping project config: /home/olle/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/olle/package.json'
5 verbose stack     at Error (native)
6 verbose cwd /home/olle
7 error Linux 4.4.0-47-generic
8 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "install:oni-plugin-typescript"
9 error node v4.2.6
10 error npm  v3.5.2
11 error path /home/olle/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/home/olle/package.json'
16 error enoent ENOENT: no such file or directory, open '/home/olle/package.json'
16 error enoent This is most likely not a problem with npm itself
16 error enoent and is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

**Comment by olleharstedt** [comment]
I get this error when running `npm install -g oni-vim`

**Comment by extr0py** [comment]
Interesting, I haven't seen this - and it looks like the npm install step is working okay on TravisCI (which is Linux). 

If you clone & build the repo, does it work?

**Comment by olleharstedt** [comment]
Yes, I could build it manually.

**Comment by erahhal** [comment]
I get the same problem on Ubuntu 16.04, but even using sudo:

`sudo npm install -g oni-vim`

For some reason a global install is trying to write to ~/.npm in my home folder, with the following error:

`npm ERR! Error: EACCES: permission denied, mkdir '/home/erahhal/.npm/oni-plugin-typescript'`
 
There's definitely something wrong here.

**Comment by hxegon** [comment]
Getting the same error as @erahhal. A little more info: it's trying to open $HOME/package.json when I try and run ```sudo npm run install:oni-plugin-typescript```.

**Comment by jetz** [comment]
Same problem on Ubuntu 16.04. ` Missing write access to /usr/local/lib/node_modules ...`

I found when install by `sudo npm install -g oni-vim`, the `oni-plugin-typescript` dir's owner in $HOME/.npm is nobody, does it matter?

**Comment by extr0py** [comment]
Hmm, I think I need to get rid of the `postinstall` script that runs `npm install` in the `oni-plugin-typescript` directory, and push those dependencies up.

**Comment by extr0py** [comment]
I've published version 0.1.2 at npm, so please try `sudo npm install -g oni-vim` again. The `postinstall` script that was causing problems was removed with #40. Thanks!

**Comment by hxegon** [comment]
Works for me :)

**Comment by erahhal** [comment]
verified that this fix worked.
