### ISSUE TITLE
VimL?

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#192]
On the side of vim script, what would you say needs done that would either mesh with or enable your future work on the JS/TS side of things.

**Comment by extr0py** [comment]
Hi @bert88sta ,

Hmm, in terms of VimScript, ONI has a pretty low surface area right now. Most of the ONI-facing functionality is in: `oni/vim/core/oni-core-interop/plugin/init.vim`

And there are three major responsibilities there:
- Send buffer updates
- Send vim-facing events that aren't captured via the `msgpack-rpc` API
- Send information about the window size / lines rendered

Also there's the set of defaults we have in `oni/vim/default/bundle/oni-vim-defaults` that could be curated. There's also some other plugin defaults we could add - I like `vim-surround` a lot, and I know @keforbes  recommend `vim-airline` as well - so we could look at adding some of those into our default set.

In terms of other contribution ideas, documentation could use some help! The README currently is kind of chaotic :)

And in terms of TypeScript & JavaScript, it's really never been a better time to get into front-end development! People are doing some amazing things with JavaScript - like [3d graphics](https://threejs.org/), [time travel debugging with hot-reload](https://www.youtube.com/watch?v=xsSnOQynTHs), [games](https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_breakout_game_Phaser). There's tons of momentum and it's a great skill to learn - you can take this and even build apps with [Cordova](https://cordova.apache.org/) and [React-Native](https://facebook.github.io/react-native/). But I really appreciate your willingness to contribute and it would be great to have your help on some of the TypeScript & JavaScript issues too!

**Comment by extr0py** [comment]
Oh just saw this in hacker news too - this is a cool React+Redux project: [react-tetris](https://chvin.github.io/react-tetris)!
