### ISSUE TITLE
Redo in edit menu not working

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#196]
@keforbes did some great work in enabling our 'Edit' menu in the toolbar - adding cut, copy, paste, put before/after, etc.

There is a strange issue with `Redo` though - for some reason, `normal! <C-r>` doesn't seem to work as expected. Not sure if this is a neovim bug or something we are doing wrong. It would be interesting to see how vim/gvim behave in that case.

It looks like the `:redo` command works, so we could potentially expand our interface for passing messages to support both `execute` and `normal!` actions (really, the `execute` is a superset anyway) - we'd just have to update our existing messages to match.

**Comment by bert88sta** [comment]
A few things. I've fixed this issue by just flat out changing it to exec

exec "normal! \<something>" is pretty explicity listed in vimdoc as being the right way to use escape sequences with normal!, so we won't have any worries there. also the single slash escape was giving it issues. The other issue I noticed here is that for me (OSX) the menu where all of this stuff works is under Electron. I think there might have to be reworking based on OS, but we can jump off of that bridge when we get to it.
