### ISSUE TITLE
Input - Keyboard: Clean up & generalize key handling

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#2]
In keyboard.ts, there is a giant switch for handling various keycodes. This isn't maintainable to handle new scenarios, and there are several keys that are currently not supported.

Some keys that should be supported:
- VolumeUp/VolumeDown
- ScrollLock
- Delete

**Comment by bert88sta** [comment]
I'm not a huge TS/JS guy at all, but what would you use besides a switch to handle the keycodes?

**Comment by extr0py** [comment]
@bert88sta - sorry, this issue wasn't very clear :) 

In retrospect the switch really isn't too bad... The bigger problem is that there are a bunch of hardcoded keybindings, like in index.tsx:

```
        if (key === "<f3>") {
            formatter.formatBuffer()
            return
        }

        if (UI.isPopupMenuOpen()) {
            if (key === "<esc>") {
                UI.hidePopupMenu()
            } else if (key === "<enter>") {
                UI.selectPopupMenuItem(false)
            } else if (key === "<C-v>") {
                UI.selectPopupMenuItem(true)
            } else if (key === "<C-n>") {
                UI.nextPopupMenuItem()
            } else if (key === "<C-p>") {
                UI.previousPopupMenuItem()
            }

            return
        }
```

So making those configurable is a more pressing issue, since I'm sure my random defaults that work for me aren't for everyone :)

There's some good discussion on this in #20 - I'm going to close this one in favor of that, since that has more details about that problem and potential solutions.
