### ISSUE TITLE
Text rendering blurry on retina.

### ISSUE THREAD

**Issue by jordwalke** [extr0py/oni#21]
I noticed that text rendering is blurry on retina screens.

**Comment by langolf** [comment]
I see the same. Here screenshot for comparison
<img width="351" alt="screen shot 2016-12-04 at 11 50 49" src="https://cloud.githubusercontent.com/assets/1225205/20865057/142e4c66-ba18-11e6-89db-c5bb5043f23c.png">

**Comment by extr0py** [comment]
Thanks for the report and screenshot! I think it may be an issue with the rendering strategy I'm using. I think https://github.com/rhysd/NyaoVim handles some of the cases a bit better, need to try it out and see.

There's a few ideas in this StackOverflow post as well-
http://stackoverflow.com/questions/4550926/subpixel-anti-aliased-text-on-html5s-canvas-element

Will do some testing and report back

**Comment by darkwater** [comment]
Aren't you drawing on quarter resolution? This looks too blurry to be the difference between pixel anti-aliasing and sub-pixel anti-aliasing. I think macOS renders applications at "normal" resolution by default, unless they explicitly intend to work correctly on retina screens. A way to test this would be to check the resolution of the canvas and see if it's how it'd be on a low-resolution screen or a retina screen (which should be double in both dimensions)

Either way it doesn't seem like the text is rendering with sub-pixel anti-aliasing anyway, but I believe that's a separate issue.

![](http://novaember.com/s/8f9453/9N6oYU.png)

**Comment by extr0py** [comment]
@darkwater - I believe you're correct. We're ignoring the `devicePixelRatio` value, which I believe on retina devices would be `2`. So we're using the device-independent pixels, which would basically render at quarter resolution. Seems like that may need to be accounted for in the canvas rendering logic and the resize logic.
