### ISSUE TITLE
Pressing `Ctrl-A` highlights everything

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#216]
Pressing `Ctrl-A` highlights everything and puts the text into a bad state. The only fix is to click with the mouse somewhere to remove selection.

We need to fix this by either `preventDefault`ing the Ctrl-A keypress, or adding some CSS such that the text does not show up as selectable.

**Comment by bert88sta** [comment]
I'm going to weigh in right now and say that CSS is the right answer, mainly because on OSX it's cmd - a which we don't handle but will still cause the same undesired effect. I know nothing about CSS but I'll see if I can throw something together

**Comment by extr0py** [comment]
Yep, seems like it would be straightforward. I think we can just use this CSS style:
https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

And add something like:

body, html {
user-select: none;
-webkit-user-select: none;
}

**Comment by keforbes** [comment]
Wouldn't it be better to prevent `Ctrl+A` from performing any action at all?  The current behavior prevents `Ctrl+A` from being mapped to anything because Electron will perform the action first.  Similarly, `Ctrl+R` will perform Electron's `Reload` action rather than NeoVim's `Redo` command.

**Comment by bert88sta** [comment]
We need to do a similar thing for Super key and prevent default on all the
bindings then.  They behave the same way but don't convert into ctrl-a.

**Comment by extr0py** [comment]
Right, that's a good point. Seems like we might want to call `preventDefault` on all actions we handle by default.

**Comment by extr0py** [comment]
Looks like this is fixed now :) Thanks @bert88sta !
