### ISSUE TITLE
Plugin API: Incremental buffer updates

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#217]
We always send over the entirety of the buffer. The vscode language service protocol, though, supports incremental updates. It seems like we could support this, especially in insert mode, by only updating the lines that have been touched.

This would also be a good opportunity to formalize the way we handle the buffer updates - like completion, the logic is spread in multiple areas. It'd be a good candidate for its own `Service`

**Comment by extr0py** [comment]
I believe this is a contributing factor as well to why typescript completion can be slow - in insert mode, even if we just add a single character, we're asking the typescript language service to reparse the entire file - and for large files, this is not trivial.

For typescript specifically: https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts

They support the `change` event which is what we want. And the Microsoft Language Service protocol also supports a similiar event.

**Comment by justinmk** [comment]
I think https://github.com/neovim/neovim/pull/5269 is intended to help with this.

**Comment by bert88sta** [comment]
@extr0py 

Sorry, is this between neovim and oni or between oni and TS server?

Could you list a few files to check out?

Thanks

**Comment by extr0py** [comment]
Yes, there's actually two main issues with the buffer updates right now.

- **neovim -> oni** - whenever the buffer is changed, we send the full buffer update to ONI. If the buffer is large, this seems like it can cause a performance hit. I did some investigation of this and put the results in #229 - it seems like there are other optimizations we can make on the `msgpack-rpc` transport layer to improve perf.

- **oni -> language service (typescript)** - once we get the full buffer update, we tell the language service that the whole file has changed. This is bad for the TypeScript language service, because it has to re-parse the entire file before it can give us completions. For large TypeScript files, this can take a non-trivial amount of time (which causes a delay in resolving the completions). The language service protocol, along with TypeScript, can take incremental updates which let the language service know it only has to re-parse / process a subset of the file.

For this issue, I was thinking about the second case - reducing the load on the typescript language service when we have a buffer update. Especially in the case when we're typing in insert mode and there are not a lot of other changes, we should be able to handle that case very efficiently. Right now, at least for my environment, this is the biggest blocker - the completions take a half second or so to populate, which is enough to be annoying.

**Comment by extr0py** [comment]
For the language service side (which was the largest bottleneck), this was addressed by #257. We can look at #229 later for further improvements.
