### ISSUE TITLE
index.html:40 GET http://localhost:8191/bundle.js net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by firedev** [extr0py/oni#22]
Hi,

When I launch `oni` in Terminal it opens an Electron windows with the following error:

```
index.html:40 GET http://localhost:8191/bundle.js net::ERR_CONNECTION_REFUSED
```

Should I run anything else other than `npm install -g oni` ?

Thanks.

**Comment by extr0py** [comment]
Hi there,

Do you happen to have the `NODE_ENV` environment variable set to `DEBUG`? 

There's code to load the bundle based on that variable:
```
        var path = "dist/browser/bundle.js"
        if(process.env.NODE_ENV === "development") {
            path = "http://localhost:8191/bundle.js";
        }
```

For use with webpack. I'd like to make this more robust in the future - potentially at least addd another environment variable.

In the meantime, can you check if the NODE_ENV variable is set? If so, clearing it when starting the process might be a workaround in the meantime. Thanks for trying it out!

**Comment by firedev** [comment]
Indeed, I have it set to `development` maybe that was a bad idea. I'll clean it up. Thanks!
