### ISSUE TITLE
node version

### ISSUE THREAD

**Issue by TalAmuyal** [extr0py/oni#220]
Hi,

I follow Oni for a few weeks and would like to give it a go.
To use/install Oni, do I need node 6.x or 7.x? (couldn't find it in the documentation)

Thanks in advance,
Tal A.

**Comment by extr0py** [comment]
Awesome! Let us know how it goes. Node 6.x+ is fine for both running and building. I'll look at adding this to the documentation in a bit.

**Comment by extr0py** [comment]
Looks like this is no longer applicable, since we now use binary releases.
