### ISSUE TITLE
Configuration: When config.js changes, trigger a reload of settings

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#236]
When a user is editing `config.js`, it'd be awesome to see the updates once the user saves. There are a couple of items we'd need for this:

- An event to listen for when configuration changes - like `Config.on("changed", (newConfig) => { ... })`
- A config file listener in Config that watches for file changes (or the save event on config.js) and reloads the new settings
- Updated the places that care about settings / setting changes to opt-in to listening for these. An example might be for the cursorLine/cursorColumn functionality

**Comment by bert88sta** [comment]
Looking at this, do you think it would be a better idea to just turn Config into a react component and put the config in the state?

**Comment by extr0py** [comment]
Some of our settings our UI driven, but not all of them. The functionality in our Current config object is mostly to load settings from the file system, and that responsibility wouldn't make sense to be a React component, since it isn't a UI functionality.

I think it does makes sense to have some of the settings in our application state - maybe even exposing a "configuration" node on our state tree. For now, what we could have happen is, listening to that Config changed event, we dispatch a `CONFIGURATION_UPDATED` action that sets that node in the tree. To start, we can explicitly add these settings to the state tree, and potentially later maybe generalize it as we start to identify a pattern.

In addition, keeping the Config loading logic separate from our UI logic helps keep our app [loosely coupled[(https://en.wikipedia.org/wiki/Loose_coupling), which is a desirable property for software because it means you can easily change out pieces of it (and it makes it easier to understand, since the pieces / areas of responsibility should stay small for each component)

**Comment by bert88sta** [comment]
@extr0py: I've got some of the boilerplate set up with listening to a save event for config.json and then emitting, is there a specific library I should be using to reload the config file? I was originally just going to change the internal declarations to let instead of const and then add a reload method, but I didn't know if that was breaking some important rules of typescript

**Comment by extr0py** [comment]
Sweet! There isn't a library you need to use, the built in `require` functionality does this:

```
let userRuntimeConfig = {}
if (fs.existsSync(userJsConfig)) {
    userRuntimeConfig = global["require"](userJsConfig) // tslint:disable-line no-string-literal
}
```

We'd just want to re-run that global["require"](userJsConfig). (We could use the `nodeRequire` utility that was added too, which does the same thing). That will get a new version of the config. We might want to tuck this in a `loadConfig` method and just re-call it.

**Comment by bert88sta** [comment]
@extr0py: I'll open a WIP PR maybe tomorrow, I'm like 15 hours a day at school because of theatre.

First, if we want to have Config.on("event"), does Config have to become a class that extends event emitter, or am I missing something? I get an error

Property 'on' does not exist on type 'typeof "/Users/Bret/oni/browser/src/Config"'

which likely means I'm missing an import of some type.

The second thing is (and this is why I naively suggested make Config a React Component) how do I put the Config settings in the state? I guess we could just make an array, but it seems like the State has to be pretty specifically defined ahead of time, which will be a pain if we end up adding the millions of config options vim users love.

**Comment by keforbes** [comment]
For whatever reason, I decided to try implementing this feature myself.  I'd just like to say that this statement is simply not true:
> We'd just want to re-run that global["require"].  That will get a new version of the config.

Re-running that require does *not* load a new version of the config.  I have everything else working but it never actually reads in the changes from the file.  I can't find what cache it's using for me to invalidate, but trying to find a way to refresh that object is taking more time than it did to implement the change.  I just wanted to complain, thank you for listening. :smile:

**Comment by extr0py** [comment]
Ah, sorry about that, you're right, I forgot that the `requires` are cached. 

Maybe this stackoverflow thread has some ideas: http://stackoverflow.com/questions/9210542/node-js-require-cache-possible-to-invalidate

Or perhaps this NPM module would be helpful as well: https://www.npmjs.com/package/decache

**Comment by keforbes** [comment]
I found that stackoverflow link too but it deals with `require('./a.js')` and you're doing `global["require"]('./a.js')` which somehow behaves differently.  I can't find the module.exports in the require cache to delete it.

**Comment by keforbes** [comment]
Nevermind, I got it.  I just had to be consistent with that `global["require"]` syntax:
```
delete global["require"].cache[global["require"].resolve(userJsConfig)]
```

**Comment by extr0py** [comment]
Ouch ya another "gotcha" - we use the `webpack` bundler with the project, and it treats require in a special way. Webpack doesn't recognize the `global["require"]`, so that's our workaround to get it to ignore those (otherwise, webpack actually tries to load the file during build time and bundle it into the JavaScript file!).

Nice find on the fix, deleting from that cache looks like it should work.
