### ISSUE TITLE
I just reinstalled oni, it won't run

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#240]
I just reinstalled oni, as in forked from extr0py/master.

When I open it up, it is just a white screen. It can't be maximized.

**Comment by keforbes** [comment]
Did you run `npm install` before building?  Is `nvim` still on your path?  I just did a rebase on my repo and I can still use Oni.

**Comment by bert88sta** [comment]
My bad, I pulled but didn't hard reset

Ignore the village idiot :)
