### ISSUE TITLE
Tone down the new cursorline

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#242]
I updated to the latest bits with @bert88sta's new cursorline implementation.  Can we bring down the color on it a bit?  Or maybe make it more transparent?  My first thought when I launched Oni was "uh oh, it started me in visual mode".  It wasn't until I moved the cursor that I noticed it was the new cursorline.

![cursorline](https://cloud.githubusercontent.com/assets/817509/23189063/5fdf0d20-f84e-11e6-88fa-2dba9d303748.png)
In the screenshot above, I'm in Visual Line mode.  Personally, I can't tell much difference between the visual highlight and the cursorline highlight.  If I'm crazy and the only one who thinks this way then I'll just accept it and close this issue, but I'd like the cursorline to be a bit darker (while still being distinct from the background).

**Comment by jonaspm** [comment]
I agree with you @keforbes

**Comment by extr0py** [comment]
Agreed - perhaps we could add a setting like ``editor.cursorLineOpacity` / `editor.cursorColumnOpacity` options to tone it down a bit? And set the default to be more transparent?

**Comment by keforbes** [comment]
I looked at the code and he's taking the color of the cursor and setting its opacity to 0.2.  That's a good idea so it keeps the cursor and cursorline looking similar despite any changes to configs but it doesn't give much transparency to work with.  It might be better to darken the cursorline using the LESS `darken()` method.  Or maybe make the visual selection brighter?  I'm not sure which one would look better.

**Comment by jonaspm** [comment]
I think that making both cursor & cursorline darker / more transparent would work.

**Comment by bert88sta** [comment]
This is the cursor line not darkened, but turned down to 0.1 opacity.


Thoughts? 

![screen shot 2017-02-23 at 9 59 58 am](https://cloud.githubusercontent.com/assets/8421641/23264317/e95eef1e-f9ae-11e6-98b7-a240317b133e.png)

**Comment by extr0py** [comment]
The `0.1` opacity on the default color scheme looks pretty good too. And it is also much dimmer than visual selection also. Let's try setting that opacity to `0.1` as the default and go with that - seems like a simple / quick fix if everyone agrees.

**Comment by keforbes** [comment]
Yeah, let's just go with the `0.1` opacity for now.  I'll probably want the visual highlight to stand out more in the future but I'll play with the `0.1` opacity for a while first and see how I feel about the visual highlight.

**Comment by extr0py** [comment]
Looks like this was fixed by #254 . If it is not fully addressed, please feel free to reopen. Thanks @bert88sta !
