### ISSUE TITLE
Add default `config.js` when going to Preferences -> Edit configuration

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#252]
@keforbes had a good idea with this PR:
https://github.com/extr0py/oni/pull/243

When we first edit the configuration, and the configuration doesn't exist, we should add a template / placeholder that shows the format, so that it is easy to modify.

Later enhancements could be to add the default settings in there, and add custom completion for that file.

**Comment by keforbes** [comment]
This is addressed in #266.

**Comment by keforbes** [comment]
#266 was merged in so we can close this issue.

**Comment by extr0py** [comment]
Thanks for the fix!
