### ISSUE TITLE
Enable clicking on items in Fuzzy Finder and Command Palette

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#265]
If you try clicking on an entry in the Fuzzy Finder or Command Palette, the click event is only registered by NeoVim (moving the cursor).

![click](https://cloud.githubusercontent.com/assets/817509/23514606/09cee6ac-ff25-11e6-9d17-e5a3f22b5a4f.gif)

**Comment by extr0py** [comment]
I use Oni as my editor at work... and these sorts of issues are embarrassing when I have a coworker trying to use it :) Thanks for opening the issue.
