### ISSUE TITLE
npm install -g oni doesn't work

### ISSUE THREAD

**Issue by tbodt** [extr0py/oni#277]
I installed oni with `npm install -g oni`, and when I run `oni` and open the developer console it says there was a 404 on `file:///usr/local/lib/node_modules/oni-vim/dist/browser/bundle.js`.

**Comment by adelarsq** [comment]
Try ```npm install -g oni-vim```

**Comment by tbodt** [comment]
dammit

**Comment by tbodt** [comment]
dammit

**Comment by extr0py** [comment]
Sorry about the confusion there... I wish I could grab the `oni` name. Thanks for catching that, @adelarsq !

I'm also considering change the name to `onivim` and grabbing that package name, so that the repo name + package name match. Let me know if you have feedback or ideas.

**Comment by keforbes** [comment]
Can we ask the owner of https://github.com/tillarnold/oni to remove `oni` from npm or is that too.... rude?  The `oni` project hasn't changed in over a year and has 0 stars.  I don't want to hurt anyone's feelings but it doesn't sound like that project has any users.

**Comment by extr0py** [comment]
Good point - worth at least reaching out to see. Logged #279 to track this further.
