### ISSUE TITLE
Get matching package name `oni`, or reserve + update name

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#279]
There is lots of confusion around this repo being `oni` and the npm package being `oni-vim`.

We should look at ways to match these up. Some discussion was tracked in #277 

A couple ideas:
- See if the owner for `oni` on npm would be willing to give us the package name
- Update the name to something that isn't already reserved.

Let me know if you have ideas!

**Comment by bert88sta** [comment]
@extr0py is your npm username also extr0py?

**Comment by extr0py** [comment]
Yep, same name on npm.

I started looking at `oni` vs `onivim` and it seems like in general `onivim` is more available:
1) `onivim.io` is available 
2) Subreddit is available: http://www.reddit.com/r/onivim
3) npm package `onivim` is available

I snagged all of those above :)

For the next release (likely `0.1.11`), I'm planning on making the switch.  If we stick with just `oni`, it'd be harder to get the rest of those collateral. Let me know if you have any concerns @keforbes @bert88sta

**Comment by bert88sta** [comment]
Oh, I talked to the guy who owns oni and he said he'd just give it to you

**Comment by keforbes** [comment]
If the guy who owns oni on npm is willing to give it to us I'd rather keep that name.  It's good to grab onivim on things like reddit since oni has another meaning, but on software-specific sites I think we should use the name oni.

**Comment by bert88sta** [comment]
This is his/her email to me

Hello

Sure, you can have the package name. My project isn't really serious.

To transfer the package to you I just run:

npm owner add extr0py oni

right?

Cheers,
Till

Is that right? I don't know about npm enough to verify

**Comment by extr0py** [comment]
Sweet! Thanks @bert88sta for reaching out - you rock.

Yes, `npm owner add extr0py oni` is all that would be needed. We should also check with Till and see if he has a twitter handle or a website he'd like us to plug - we should put a special thanks message in our README.md like "Special thanks to Till for handing over the `oni` NPM package name", with a link to his website/twitter. Not that we can get a lot of traffic now, but maybe one day ;)

**Comment by extr0py** [comment]
And ya, since you did all this legwork, I agree - having the `oni` name would be awesome, we'll stick with that as our name. I do prefer having a short, easily identifiable name.

I have the onivim subreddit and onivim.io domains - it's a bummer we can't get just `oni` for those, but not the end of the world.

**Comment by bert88sta** [comment]
Hello

I just transferred the package.

You don't have to thank me in the README, but if you really want to you can
just reference my github handle @tillarnold

Cheers,
Till


Quoted from the email to me

**Comment by extr0py** [comment]
Awesome! It's up at npm: https://www.npmjs.com/package/oni

I'm adding a deprecation notice to the `oni-vim` npm package. Thanks for all the help!

**Comment by extr0py** [comment]
Aaaand https://www.npmjs.com/package/oni-vim is marked as deprecated. Thanks all for the help, and especially @tillarnold for giving us the package name. Cheers!
