### ISSUE TITLE
How run it on windows？

### ISSUE THREAD

**Issue by kdurant** [extr0py/oni#28]
What needs to be done to prepare?

I had download it。

**Comment by extr0py** [comment]
Windows binaries are included, so if you used npm, `oni` or `oni-vim` at the command line will start the app.

If you used git clone, you'll need to run `npm install`,  `npm run build` and `npm link` and then you should be able to run it.

Are you hitting an error when you try to launch?

**Comment by kdurant** [comment]
I download zip file, and `cd` oni-0.1.1 directory. But can't run `oni` or `oni-vim` at the command line

**Comment by extr0py** [comment]
Ah, if you downloaded the zip file, you'll need to build and run:

- `npm run install`
- `npm run build`
- `npm run link`

**Comment by kdurant** [comment]
@extr0py 
![qq 20161207103720](https://cloud.githubusercontent.com/assets/2704364/20952696/355949ce-bc69-11e6-83a8-5a7c974e2cd0.png)

**Comment by extr0py** [comment]
Oops, try `npm install`

**Comment by kdurant** [comment]
@extr0py 
![qq 20161207103720](https://cloud.githubusercontent.com/assets/2704364/20952881/8068ec34-bc6a-11e6-8fec-83a7eb4a8d5d.png)

**Comment by extr0py** [comment]
That output looks right, now you need to do:
`npm run build`
`npm run start`

**Comment by extr0py** [comment]
Minor tweak- you might want to do:
`npm run build`
`npm link`
`oni'

**Comment by extr0py** [comment]
Will close this out since I don't believe any further action is required - but lmk if you are still having trouble running it. Thanks!
