### ISSUE TITLE
Start oni on terminal

### ISSUE THREAD

**Issue by Batou99** [extr0py/oni#282]
Is it possible to start oni inside an `hyper` terminal instead of opening a new electron window?
If I understand correctly how oni works it opens an electron frame, so why not reuse the one the terminal has already opened?

**Comment by extr0py** [comment]
Interesting, I actually haven't used `hyper` but it looks like a cool project.

In theory, it should be doable - in practice, there might be some tricky aspects - there are things that we handle outside the BrowserWindow (like ensuring a single instance and communicating between Oni processes). In addition, there are potential issues with conflicting electron versions.

Personally, I'm more interested in the opposite scenario - hosting a terminal inside Neovim / Oni - but I'm open to PRs here if this is something that would be useful to others. Thanks for the suggestion!
