### ISSUE TITLE
Error: 0, Vim(call):E121: Undefined variable: api_level

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#287]
Seeing an error on launch in Windows:
![image](https://cloud.githubusercontent.com/assets/13532591/23804355/6b7a8ce0-056e-11e7-96cc-7e504cefb12f.png)

I think this is related to the recent api_level change made by @bert88sta 

I wonder if the packaged neovim binary for Windows is older - the potential fix could be either to revise the logic, or upgrade our neovim binary.

**Comment by bert88sta** [comment]
@extr0py : Nope, i'm just forgetting quotes when I send back {api_level:0}, check #288

**Comment by extr0py** [comment]
With #288, the error message is improved, but it's confusing on Windows - neovim 0.1.6 is included in the package, but I still get the error. I need to check and see if I should upgrade the binary or if the version in api_info is coming across differently

**Comment by justinmk** [comment]
It shouldn't have changed. But I definitely recommend using the latest binary, tons of fixes for Windows in 0.2

**Comment by extr0py** [comment]
Thanks @justinmk, look forward to testing out these fixes!

**Comment by extr0py** [comment]
Fixed by #289

**Comment by extr0py** [comment]
Clipboard integration seems to work much better in 0.2.0 on Windows... awesome!
