### ISSUE TITLE
Missing parenthesis

### ISSUE THREAD

**Issue by gglanzani** [extr0py/oni#29]
Hi all, 

I'm trying to run :CheckHealth, but I do get this error:

```
C:\Users\x\AppData\Roaming\npm\node_modules\oni-vim\vim\vimfiles\jedi-vim\autoload\health\jedi#check
================================================================================
  - ERROR: Failed to run healthcheck for "C:\Users\x\AppData\Roaming\npm\node_modules\oni-vim\vim\vimfiles\jedi-vim\autoload\health\jedi#check" plugin. Exception:
    Vim(call):E107: Missing parentheses: C:\Users\x\AppData\Roaming\npm\node_modules\oni-vim\vim\vimfiles\jedi-vim\autoload\health\jedi#check()
```

I'm using Windows 10, installed oni via npm

**Comment by extr0py** [comment]
Hi there,

Interesting, I just tried it too, and see a similiar issue:

```
D:\oni\bin\x86\Neovim\share\nvim\runtime\autoload\health\nvim#check
================================================================================
  - ERROR: Failed to run healthcheck for "D:\oni\bin\x86\Neovim\share\nvim\runtime\autoload\health\nvim#check" plugin. Exception:
    Vim(call):E107: Missing parentheses: D:\oni\bin\x86\Neovim\share\nvim\runtime\autoload\health\nvim#check()

D:\oni\bin\x86\Neovim\share\nvim\runtime\autoload\health\provider#check
================================================================================
  - ERROR: Failed to run healthcheck for "D:\oni\bin\x86\Neovim\share\nvim\runtime\autoload\health\provider#check" plugin. Exception:
    Vim(call):E107: Missing parentheses: D:\oni\bin\x86\Neovim\share\nvim\runtime\autoload\health\provider#check()

```

These look like the Neovim/vim runtime plugins.

Regarding jedi-vim, there could be a  separate issue, though - I've packaged a Windows neovim binary, but it doesn't have python support.  For the version I've bundled, it doesn't look like it has python support, as `echo has('python')` and `echo has('python3')` both return false. You might want to try modifying it to use your build. You can modify that it in NeovimInstance.ts when it spawns the process at the bottom. We should have a Config setting for this too.

**Comment by gglanzani** [comment]
@extr0py Thanks!

I still have to build a neovim for Windows. I'll probably download it from the AppVeyor CI then.

I'll try to let you know (maybe tonight).

**Comment by gglanzani** [comment]
@extr0py It seems that even with the latest binaries there's no Python luck.

See https://github.com/neovim/neovim/issues/5360 (in particular this bit https://github.com/neovim/neovim/issues/5360#issuecomment-249855604 ) and the PR that should fix it is still open https://github.com/neovim/neovim/pull/5280

I guess I'll patiently wait ;)

**Comment by extr0py** [comment]
Ya, bummer :( I was looking for a distribution too with Python so I could use Ultisnips but no luck. I'll close this for now then, since it's tracked by a Neovim issue.

The good news is I believe we could still support a python language service like Jedi, even without Python integration directly in Neovim. If you're interested in that, we can track in a separate issue. I'll close this for now though since it's not an Oni issue.

Cheers!

**Comment by gglanzani** [comment]
I would wait first for Python support for nvim on Windows. It's a target for 0.2 anyway, and work is underway.

This could save us lots of time.

**Comment by justinmk** [comment]
FWIW, CheckHealth should work in Windows using the neovim HEAD build (now linked from AppVeyor).

**Comment by extr0py** [comment]
@justinmk - Nice! Thanks for the update! I'll pick up the binaries soon

**Comment by justinmk** [comment]
@extr0py If you were previously using the binaries from neovim/neovim/810 I'd wait ~1 week. I'm working on merging all the remaining Windows patches to master, in an effort to get Windows support up to par.

**Comment by extr0py** [comment]
@justinmk - cool, thanks for the heads up! I'll wait for the Windows patches to make it in.
