### ISSUE TITLE
Highlight the wrong parts while searching in the command palette?

### ISSUE THREAD

**Issue by guilhermeleobas** [extr0py/oni#304]
![image](https://cloud.githubusercontent.com/assets/2712115/24087281/d43f4df8-0cfb-11e7-9c48-980a1c059065.png)

_"Open"_ keyword should be highlighted.

**Comment by bert88sta** [comment]
I'd like to add to this as well, if you open and search for "init.vim" it
doesn't pop up, despite being an exact result. Um jot sure this this is a
search algorithm bug or just a result of fuzzy searching, but it's an issue

**Comment by keforbes** [comment]
It's an issue with the search algorithm.  It's looking at the entire path and removing a character from the search string as it finds a match.  You can see it highlighted `o`, `p`, `e` in the path and by the time it got to the filename it only had `n` left in the search string.

I don't know if we need to search the filename first or allow for characters in the search string to happen multiple times.  I've been giving this some thought but I don't have a good solution yet.

**Comment by bert88sta** [comment]
I don't know how taxing it is, but sequence matcher or a rough search on
the actual filename and then on the full path but with lower precedence
would be a good start.

**Comment by extr0py** [comment]
Yep, the algorithm is a bit busted. Most of this happens in `browser\src\UI\Reducer.ts` in `fuzzyMatchCharacters`.

**Comment by extr0py** [comment]
Might be worth replacing the algorithm we're using with a library like [fuzzy](https://www.npmjs.com/package/fuzzy).

**Comment by extr0py** [comment]
This library also looked interesting: http://fusejs.io/

**Comment by keforbes** [comment]
Created #306 using fuse.js.
