### ISSUE TITLE
Oni not started when `npm install` locally

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#321]
When installing NPM locally, it doesn't seem to run from the .bin folder.

1) Create a test folder
2) Install oni via `npm install oni`
3) Run `.\node_modules\.bin\oni` (or `oni.cmd` on Windows)

Expected: Oni should open
Actual: Oni does not open

**Comment by extr0py** [comment]
This path resolution logic doesn't seem correct here, for this case:

```
// In Windows, directly call into the electron executable - otherwise we"ll end up with a floating node console
var nonWindowsElectronPath = path.join(__dirname, "..", "node_modules", ".bin", "electron")
var windowsElectronPath = path.join(__dirname, "..", "node_modules", "electron", "dist", "electron.exe")
var spawnProcess = isWindows ? windowsElectronPath : nonWindowsElectronPath
```

We make the assumption that node_modules will be at the oni root, but looks like, in the local install case, that might not always be true. Maybe we need to revise this to search upwards for the node_modules/electron folder, and launch it from there

**Comment by keforbes** [comment]
Making that script more robust is definitely a good idea, but for the specific use-case, would it make more sense to release a self-contained .tar.gz or something for Linux along with the Windows .exe and MacOS .app in #312?  I don't know if a local `npm install` is the best route for users who just want to play with Oni locally.  If we can just .tar.gz a working directory in Linux I wonder if that would be enough.

**Comment by extr0py** [comment]
Good point, #312 is really the way forward here - having platform-specific builds that don't depend on Node/NPM will be a huge step forward for this project.

**Comment by extr0py** [comment]
I'll close this in favor of investing in #312 . FYI @teto
