### ISSUE TITLE
Inaccurate Clicking

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#322]
This is on OSX, don't know if that has anything to do with the problem but it's become quite frustrating

https://i.gyazo.com/75e6af8103323a0ba854222008a8fdf7.gif

The gif may not be entirely clear, but I'm clicking continuously and it doesn't move up to the next line until maybe 1/3 or 1/2 of the way up the next line

**Comment by extr0py** [comment]
Hmm, might have something to do with our logic in `_convertEventToPosition` in `Mouse.ts` - maybe `round` is the wrong thing to do? It seems like the coordinates maybe are getting clamped the wrong way. We might want to experiment with that function and see if we can get better results.
