### ISSUE TITLE
UI - Error Marker: Error Marker overlaps error at end of line

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#335]
The error marker UI is very helpful for real-time feedback of issues and problems in the code, however, our current design is impractical if the error is at the end of the line.

![image](https://cloud.githubusercontent.com/assets/13532591/24554927/2704b618-15e4-11e7-9f1a-c003b9ec176a.png)

In this case, the error overlaps the problem, so it is very difficult to fix.

A good inspiration for fixing this would be Atom's error message:
![image](https://cloud.githubusercontent.com/assets/13532591/24554958/3f0f2d1a-15e4-11e7-8a5e-aeafb8386e1a.png)

It shows up below the line, which makes it easier to work with. This adds a bit of complexity, because we have to decide whether to show it above or below the line (we'd want to show it above if the line is near the bottom of the screen). But the user experience would be much better.

**Comment by keforbes** [comment]
Fixed by #357.
