### ISSUE TITLE
Automatic change of mode(to INSERT mode) after ALT+TAB

### ISSUE THREAD

**Issue by JakubJecminek** [extr0py/oni#34]
On Windows, when Oni is in normal mode and I use ALT+TAB to go to different window, Oni automatically switch itself to INSERT mode.

**Comment by extr0py** [comment]
Thanks for reporting! I think it might be interpreting Alt-Tab wrong, and actually firing the 'A'.

Putting a breakpoint  in the keydown event listener in https://github.com/extr0py/oni/blob/master/browser/src/Input/Keyboard.ts would be a good place to start if someone wants to take a look

**Comment by JakubJecminek** [comment]
If it's ok I would take this bug. I will have time this week so I can work on it.

**Comment by extr0py** [comment]
Sweet! Thanks for the help, @JakubJecminek
