### ISSUE TITLE
Issue starting for first time

### ISSUE THREAD

**Issue by FrigoEU** [extr0py/oni#342]
Hey, love the project and support excited about its future!

I had a problem first starting it though. Electron started, and I just got a blank white screen. After some debugging (I only managed it with npm run start), I found that I was missing a .oni folder. I had to make it manually. 

I thought I'd let you know since it can be a real downer for first time starters to just get a blank screen.

**Comment by extr0py** [comment]
Thanks for the report @FrigoEU and for digging in to debug it!

Just a couple questions:
- Which platform is this?
- Which installer package did you use?

Appreciate the heads up!

**Comment by extr0py** [comment]
I'm not able to reproduce this with the Windows binary or with the Mac dmg - but let me know which platform you used. I'm wondering if it is there is a different configuration on my machine, or if I haven't tested the right platform. Thanks for your help!

**Comment by mixedCase** [comment]
I can reproduce this on Arch Linux. Had to create a ~ /.oni directory for it to work.

**Comment by FrigoEU** [comment]
I'm on OSX 10.11.4. 

I started out building from source, got that error. Then I used the Mac dmg, same thing. I built from source a few more times, still the same thing. Then I started up the hot reload build, and immediately got the error in the dev tools so I finally found it like that.

I'm on a fairly ordinary system and don't think I have anything special set up anywhere. Really wish I could pinpoint the problem, sorry!

**Comment by keforbes** [comment]
I was able to reproduce this in Linux.  Fixed in #347.  Thanks for catching it!

@extr0py, since this affects a user's first impression of Oni I'd recommend rolling out a new release with the fix. :smile:

**Comment by extr0py** [comment]
Thanks all for the details, and @keforbes for the quick fix! I'm able to reproduce it by removing my `.oni` folder. I'll pick up @keforbes fix ASAP and push out a new release.

**Comment by extr0py** [comment]
I'm hoping that #298 will help build a safety net for this in the fture - running a quick integration test where start up the app and validate some simple scenarios. This would've helped here since the build machines wouldn't have had a `.oni` folder

**Comment by extr0py** [comment]
Release has been updated: https://github.com/extr0py/oni/releases/tag/v0.2.2-recovery
