### ISSUE TITLE
Windows Installer: Add option to add Oni to %PATH%

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#344]
Oni should be available on the %PATH% in Windows, so that a user can type `oni` from a terminal and start up Oni.

The installer currently provides no option to do this - we should add a checkbox / option that states `Add Oni to %PATH%`

**Comment by CrossR** [comment]
This was added with #613.

**Comment by extr0py** [comment]
Verified it's working for me with the latest Windows installer - nice!

**Comment by extr0py** [comment]
I guess you can't claim the bounty until the issue is closed - bountysource should give you a "Claim Bounty" option now.
