### ISSUE TITLE
Move config options to Redux store

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#353]
One question that has come up a few times as we're working on some new UI work is whether config options belong in the Redux store. 

If the config options are _not_ in the Redux store, that means the React components are not _pure functions_ and that has some implications on hot-reloading, unit testing, etc. 

If the config options _are_ in the Redux store, it means there might be a bit of extra book-keeping / maintenance when adding new 

However, given the tradeoffs, I believe the right approach is to move these to the Redux store, and when we get the config changed event, we could populate a `configuration` branch of our state tree with these values.  We could have a generic `setConfigurationValue` action that would take a key and a value, to make these easily accessible in our components.

**Comment by keforbes** [comment]
Fixed by #356.
