### ISSUE TITLE
Cannot figure out how to install on OSX

### ISSUE THREAD

**Issue by meain** [extr0py/oni#36]
Need a bit of help installing it on macOS. I installed the npm package but it won't start.
What do you mean by `ensure the 'nvim.exe' is available`? I do have neovim installed via homebrew.

**Comment by bert88sta** [comment]
Uh, just mean you have to have a neovim executable available on MacOS. What error do you get when you type 'oni' in the shell?

**Comment by tbodt** [comment]
I've run into the fact that the oni executable has Windows (CRLF) line endings, which screws up the shebang line and gives the error `env: node\r: no such file or directory`. I opened it in Neovim, did `:set fileformat=unix` and saved, and that was fixed.

**Comment by extr0py** [comment]
Bummer - thought this was fixed in the last npmjs update. I'll revisit it, it seems like publishing from a Windows machine is problematic.  Thanks for the details

We might need a .gitattributes file to have git ignore the line ending conversion for this file.

**Comment by Gajit** [comment]
I'm having similar problems, the install looks like it's erroring out at 
> npm run install:oni-plugin-typescript.

**Comment by extr0py** [comment]
@Gajit - might be #19 also. I'll take a look at that one tomorrow, looks like quite a few people are hitting that

**Comment by extr0py** [comment]
I published a new version to NPM - 0.1.2.

I believe the line-endings issue should be fixed now. I downloaded the tarball here:
https://registry.npmjs.org/oni-vim/-/oni-vim-0.1.2.tgz

And validated that the line endings are LF in the cli/oni file. Hopefully that means users won't need the :set fileformat=unix workaround. Let me know though if that is still showing up!

**Comment by Gajit** [comment]
Ok I was able to npm install now but when Oni starts up it just gives a blank screen. Console errors with a Failed to load resources on
> file:///usr/local/lib/node_modules/oni-vim/dist/browser/bundle.js Failed to load resource: net::ERR_FILE_NOT_FOUND
