### ISSUE TITLE
Cannot read property `setMenu` of null

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#392]
Occasionally, this error pops up:
![image](https://cloud.githubusercontent.com/assets/13532591/25197751/e835bd9a-24f9-11e7-9ce9-68fc1c50d1c5.png)

It never occurs on first launch. Only when launching a second instance, and not all the time.

The following repro seems consistent:
1) Open `oni` at command prompt
2) Open a second instance of `oni`
3) Close second instance
4) Open another instance

At this point, I see the `Cannot read property 'setMenu' of null` error message. Might be a bug with how we are handling the lifecycle of the browserwindow or menu.

**Comment by keforbes** [comment]
Addressed by #394.
