### ISSUE TITLE
Vundle plugins from my config isn't initializing

### ISSUE THREAD

**Issue by unclechu** [extr0py/oni#398]
I've just build app from 1aa7f4126414d33810aa9499b8dce4e190e02f86 commit by [README](https://github.com/extr0py/oni/tree/1aa7f4126414d33810aa9499b8dce4e190e02f86#build) instructions and sourced [my config](https://github.com/unclechu/neovimrc/blob/795c052f9fe20f8f6d1288e3185d21851e873b6f/init.vim) by command: `source ~/blablabla/init.vim`. Config was applied but none of specified plugins by `Plugin` command were initialized.

```
$ uname -a
Linux fedorafarm25 4.10.10-200.fc25.x86_64 #1 SMP Thu Apr 13 01:11:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ cat /etc/fedora-release 
Fedora release 25 (Twenty Five)
```
```
$ nvim --version
NVIM v0.2.0-dev
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/build/config -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/src -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/.deps/usr/include -I/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/build/src/nvim/auto -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-1338-g263849b/build/include
Compiled by unclechu@fedorafarm25

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/unclechu/neovim-v0.2.0-1338-g263849b/share/nvim"
```
I can't execute for example `NERDTree` command or `CtrlSpace`, it gets me an error 'not an editor command'.

**Comment by ohle** [comment]
Have you tried setting `"oni.loadInitVim"` to `true` in `~/.oni/config.js` (or preferences -> edit ONI config from the main menu) instead of sourcing?

**Comment by unclechu** [comment]
@ohle this way it's working, thanks. I wonder why it doesn't work by sourcing?

**Comment by ohle** [comment]
I'm not really sure, but there are some subtle ways in which `init.vim` loading is special. Probably load order and the construction of the runtimepath has something to do with it.

I'd guess that if you start regular neovim with `-u NONE` to skip your `init.vim` and then `:source` it later, you'd run into the same problems.

**Comment by unclechu** [comment]
@ohle you're right, it's true, I have the same situation with `nvim` TUI, so this isn't connected to the Oni. Thank you again for clarifying it for me, I'm closing this issue because it solved by setting `oni.loadInitVim` option to `true`.
