### ISSUE TITLE
Need better application icons

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#4]
Need some better icons for the application:

1) Title bar
2) Dock bar in OSX

Right now, there is just a placeholder green dot, and the default electron logo comes through in a few places on OS X.

Also, a logo would be awesome for the README

**Comment by bert88sta** [comment]
This is just a poopy rough draft that I came up with, I'm by no means a graphic designer, so I won't be offended if anyone thinks it's bad. It's just a concept, someone with more talent than me could maybe work off of it
![oni](https://cloud.githubusercontent.com/assets/8421641/20868511/7733ba90-ba2b-11e6-90f1-c97da9d1a801.png)

**Comment by extr0py** [comment]
Woah, this is awesome! Looks really cool - thanks for taking the time to do this!

It'd be great to use smaller versions of this as our app icon. But in the meantime, would you be up for sending a pull request to have this at the top of the README? We might need to size it down a bit - maybe 50% or so - but would look pretty nice there

**Comment by bert88sta** [comment]
Alright, and what size would you want for the app icon? I just need a resolution number.

**Comment by jordwalke** [comment]
I would love to help with enlisting a professional graphic designer. Please get ahold of me if you're interested.

**Comment by extr0py** [comment]
@jordwalke  - that would be incredible! What's the best way to chat about this?

An app icon / logo is a great starting point - there are some other long-term ideas I'm tossing around in terms of having a great first-run / unboxing experience, and potentially an improved vimtutor, etc. All of that would be a ways out though

**Comment by jordwalke** [comment]
Do you have a Twitter account? You can chat with me there.

**Comment by extr0py** [comment]
@bert88sta  - not sure if you saw this, but on the Neovim newsletter they called out:

> ONI is an Electron-based Neovim IDE showing many exciting possiblities. It also has a __cool logo__ like NyaoVim :)

Thanks for the contribution!

**Comment by extr0py** [comment]
@jordwalke - I should probably break down and get a twitter account at some point :) I'll get an account and hit you up on there

**Comment by jordwalke** [comment]
Great!

**Comment by keforbes** [comment]
I know we already have an icon but I had an idea that I wanted to share.  I wanted to combine the Neovim 'N' logo with a japanese oni mask.  My mockup isn't great but someone might be able to take this concept and... make it better.
![oni-test](https://cloud.githubusercontent.com/assets/817509/21707206/b4a8241a-d38a-11e6-898b-663d2741e8b0.png)

**Comment by extr0py** [comment]
@keforbes - cool concept! Thanks for mocking it up and sharing it!

**Comment by extr0py** [comment]
I've been trying to experiment a bit and look at a simpler logo - something a bit abstract.

Here's one prototype I came up with:

![image](https://user-images.githubusercontent.com/13532591/29071446-89c880e8-7bf8-11e7-8d91-5b6380d9b767.png)

**Comment by cyansprite** [comment]
@extr0py 
it's really pretty but I don't think neovim when I see it, I think we might need some reference to it as well... maybe something like take the big circle with the gradient in the background, overlay/burn/diff the neovim logo onto it, then place the second smaller circle on top of it so it's behind it.

What does <i>Oni</i> mean to you?

I think of yokai and brother.

Maybe we could integrate some kind of horns or fangs elegantly like the triangle makes me think of that.
And the overlay of neovim could be like the brother...

But yes, I like it :+1:

**Comment by extr0py** [comment]
@cyansprite , thanks for the feedback!

> it's really pretty but I don't think neovim when I see it,

I think it's actually okay for the logo to be a bit more "abstract". It sets an expectation that, even though Oni is built around Neovim, there may be some differences (for example, plugins authored in JavaScript). I think this is an important consideration - if someone opens Oni and expects `nvim-qt`, they may be disappointed (ideally, if Oni is done right, they'd be _delighted_ by the changes - but that won't be every case). Because the icon is such a small canvas, it can be tough to fit in everything!

> What does Oni mean to you?

Actually I didn't realize the Japanese word until later when I googled it 😄 Originally in my mind Oni was an acronym (which is why I used to capitalize it as ONI) - and it stood for __O__ pionated __N__ eovim __I__ DE. I like the meanings though, and I think they are cool / fitting

Here are some of the design considerations I had for the logo (i drew up like 20 or so the other day, this was the only one that made it to be finally baked);
- _Colors_ should be evocative of Neovim. I wanted to preserve the green / blue to be consistent with the Neovim logo. The default colorscheme also uses these green & blue for insert and normal mode in the status bar.
- _Clean_, _simple_, _modern_ - these are design goals for Oni - although we haven't met these yet..

I used the triangle to represent the vim core - the foundation for the editing experience. 

And the orbiting circle to represent electron (since Oni is basically a vim core - powered by Neovim - plus electron functionality outside).

Other than that I just want something simple, sleek, that looks like it is at-home in the OSX dock.

**Comment by extr0py** [comment]
Here's a draft of a headline / splash image as well:

![image](https://user-images.githubusercontent.com/13532591/29077903-f07ae028-7c0d-11e7-928e-e1fcdd5de1e3.png)

I used the [Orbitron](https://fonts.google.com/specimen/Orbitron?query=orbi&selection.family=Orbitron) font to convey sort of a futuristic / modern / high-tech feel.

**Comment by keforbes** [comment]
@extr0py, I actually love the new logo.  I agree you want something simple so it is still recognizable at 16x16 pixels but smooth enough that it looks good at higher resolutions.  I think the blue/green gradient *is* reminiscent of Neovim and I like how the triangle in the middle is almost like a 'v' for vim. 👍

**Comment by extr0py** [comment]
Nice, thanks @keforbes ! 😄 Great to hear.

**Comment by cyansprite** [comment]
What release would we add it?

**Comment by extr0py** [comment]
@cyansprite - I'm planning on bringing this in as part of the next release (0.2.8).
