### ISSUE TITLE
Is it possible to connect to existing nvim instance?

### ISSUE THREAD

**Issue by unclechu** [extr0py/oni#400]
Neovim could be started as daemon with `--headless` mode and then some GUI could be connected to it. For example:
```bash
$ env NVIM_LISTEN_ADDRESS=/tmp/myneovimsocketfile nvim --headless
```
And GUI could be attached to it:
```bash
$ nvim-qt --server /tmp/myneovimsocketfile
```
It is useful when you start this daemon in **tmux** and nothing bad happened if you accidentally close neovim GUI window, or even terminal with opened **tmux**, you could always reattach to **tmux** session or to Neovim daemon by opening GUI again. You could also stop at the middle of your work and close these windows, and then, later, you could get back to work in few moment just reattaching to nvim daemon.

My question is, is it possible with the Oni? `--help` argument gets me nothing. If it's not, then I suggest to implement this feature.

**Comment by keforbes** [comment]
This is currently being worked on as #299

**Comment by extr0py** [comment]
Yep, it looks like this is tracked by #246 (help on command line) and #247 (remote capabilities). I'll resolve this as a duplicate but let me know if there is something additional we should track. Thanks!
