### ISSUE TITLE
Can't fullscreen, power line fonts broken.

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#403]
![screen shot 2017-04-25 at 2 09 24 pm](https://cloud.githubusercontent.com/assets/8421641/25400553/faae95a2-29c0-11e7-9e6b-e02a5283b4fc.png)

Resizing works, but the fullscreen button does not

Also, the fonts are not the ones specified in my oni config.js

**Comment by bert88sta** [comment]
I installed from npm and it worked. I'm not sure how different npm is from the git version, but hopefully that narrows down the issue

**Comment by extr0py** [comment]
Weird - I'm assuming by git version, you mean building from sources? Or did you install the dmg via the Releases tab (https://github.com/extr0py/oni/releases)?

The `npm` version is a bit outdated - I've added a deprecation page to the entry for `oni` on npmjs.org. It's strange that your config isn't loading, though. Might be worth putting a breakpoint in the `configChange` handler in `browser/src/index.tsx` to see what it is picking up in terms of `editor.fontFamily`.

**Comment by bert88sta** [comment]
I built from source when it happened, I don't know  if it's on my end or
yours, but I installed (npm install oni) and it fixed. It's the same thing
that happens when I run it out of tmux, but I wasn't using tmux at the time

**Comment by extr0py** [comment]
Interesting - I wonder if it is picking up the right config file. I'll see if I can repro in OSX + tmux later on.

**Comment by bert88sta** [comment]
@extr0py : I've managed to completely break everything... What's the best way to purge node/oni stuff?

:(

**Comment by extr0py** [comment]
Bummer! 

You probably want to remove the npm-installed version of oni by doing `npm rm -g oni` (and potentially `npm rm -g oni-vim` might be around). 

Once you've uninstalled the global installations, I'd recommend doing the following from the `oni` folder:
- `git clean -dxf`
- `git pull origin master`
- `npm install`
- `npm run build`
- `npm link`

That should give you a clean slate to work with-

**Comment by bert88sta** [comment]
@extr0py : I did all that, deleted everything, and got an omnisharp error... maybe I'll just come back later

**Comment by bert88sta** [comment]
@extr0py : I got everything to install correctly, then I ran it in tmux and it broke, and the breaking persisted to after the end of the tmux session. I can fix by fresh installing, so I'll leave this up to track breaking in tmux
