### ISSUE TITLE
Ctrl+PageUp/Ctrl+PageDown bindings don't work

### ISSUE THREAD

**Issue by unclechu** [extr0py/oni#404]
I have bindings like this;
```viml
" moving tabs
nnoremap <C-S-PageUp>   :tabm-1<CR>
nnoremap <C-S-PageDown> :tabm+1<CR>

" jump by half of screen by pageup/pagedown
nmap <PageUp>     <C-u>
nmap <PageDown>   <C-d>
xmap <PageUp>     <C-u>
xmap <PageDown>   <C-d>
" default jump by pageup/pagedown with shift prefix
nmap <S-PageUp>   <C-b>
nmap <S-PageDown> <C-f>
xmap <S-PageUp>   <C-b>
xmap <S-PageDown> <C-f>
```
But only these works in the Oni:
```viml
nmap <PageUp>     <C-u>
nmap <PageDown>   <C-d>
xmap <PageUp>     <C-u>
xmap <PageDown>   <C-d>
```

**Comment by extr0py** [comment]
Thanks for the issue! There are a few places where we are hard-coding keybindings in the code (while working on a full solution for #20). Out of the box, `<C-PageUp>` and `<C-PageDown>` switch between active Oni processes, but I think I may be the only one using that functionality and it isn't well documented.

They are hardcoded here in `browser/src/index.tsx`:
```
        if (key === "<f12>") {
            commandManager.executeCommand("oni.editor.gotoDefinition", null)
        } else if (key === "<C-p>" && screen.mode === "normal") {
            quickOpen.show()
        } else if (key === "<C-P>" && screen.mode === "normal") {
            tasks.show()
        } else if (key === "<C-pageup>") {
            multiProcess.focusPreviousInstance()
        } else if (key === "<C-pagedown>") {
            multiProcess.focusNextInstance()
        } else {
            instance.input(key)
        }
```

For the `<C-pageup>` and `<C-pagedown>` bindings, we could do an interim solution while #20 is in progress:
- Create __commands__ to represent these, like `oni.nextActiveProcess` and `oni.previousActiveProcess`
- Create a VimL bridge for executing commands (like `OniExecuteCommand('oni.nextActiveProcess')`), and then in my `init.vim` I can include these bindings. Once the work for #20 is complete, I could include these in `config.js` instead.

**Comment by bert88sta** [comment]
@extr0py I think we should have a list of Oni commands based on object lookup defined by key mappings. This would make it so that you could define oni operations in your config.js and then have them mapped to a fast object lookup. This way we can avoid if-statements piling up and not have any hardcoding of keys.

**Comment by extr0py** [comment]
@bert88sta - 👍 , I agree, this seems like a natural time to even bring in a `keybindings.js` so we can stop baking in commands and start having them be configurable. This would remove a large chunk of if-statements especially in `index.tsx`.

**Comment by bert88sta** [comment]
I don't know how we'd return the functions though given that there are
quite a few objects/modules. We could construct it at the beginning of
index.tsx, but I'm not sure that would be optimal

**Comment by extr0py** [comment]
With PR #633 , you can now opt-out of the default pageup/pagedown behavior.

You'll need to add these to the `activate` method of your config.js:
```
// Opt-out of default bindings for pageup/pagedown
oni.input.unbind("<c-pageup>")
oni.input.unbind("<c-pagedown>")
```

**Comment by extr0py** [comment]
I'll close this for now, but let me know if you have any questions, or feel free to reopen if this doesn't solve the problem.
