### ISSUE TITLE
DOM Renderer: Unicode characters are occasionally wrapped

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#406]
Split this out from #402, since this seems related to our rendering strategy. In some cases, the text size isn't being measured correctly for multibyte characters, and if the containing element is not properly sized, it will cause the text to wrap, which then causes visual artifacts.

#290 is related, and the fix is likely in a similar place.

`nvim` TUI:
![neovim-oni-gui-unicode-issue-1-should-be](https://cloud.githubusercontent.com/assets/799353/25430085/c12bfd36-2a94-11e7-9734-f5986fb4cac4.png)
![neovim-oni-gui-unicode-issue-2-should-be](https://cloud.githubusercontent.com/assets/799353/25430084/c12a3d52-2a94-11e7-90a0-a439cfefddc4.png)
Oni:
![neovim-oni-gui-unicode-issue-1-bug](https://cloud.githubusercontent.com/assets/799353/25430100/cb783e26-2a94-11e7-825d-8d3f46e8eef7.png)
![neovim-oni-gui-unicode-issue-2-bug](https://cloud.githubusercontent.com/assets/799353/25430101/cb78569a-2a94-11e7-8d07-5727145d0465.png)

**Comment by keforbes** [comment]
Closing this defect as it was confirmed fixed in #402.

**Comment by extr0py** [comment]
Thanks @keforbes !
