### ISSUE TITLE
Windows: Omnisharp plugin requires administrator permissions to download

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#423]
__Issue__:

In distribution builds, on Windows, the Omnisharp (C#) language service requires administrator privilege to download the windows client. The install location on my machine, for example, is here:
"Downloading C:\\Program Files (x86)\\Oni\\resources\\app\\node_modules\\omnisharp-client\\omnisharp-win-x64-net46\\omnisharp-win-x64-net46.zip"}

Therefore, downloading this in a non-administrator context will result in the download failing.

__Potential Fixes__:
- OPTION 1: See if there is a way to override the download / binary location for this. Potentially in the cache / userData folder of electron, or some of other writable place.
- OPTION 2: Copy the default or select plugins to the cache / userData folder on startup.
- OPTION 3: Package the downloaded file during windows install. This means the installation size is even larger, which would not be ideal.

**Comment by cyansprite** [comment]
I use c# heavily with Unity, I will see if I can fix this at some point...
Assuming I get time :P.
Also might add on to your plugin, great idea to have it as a plugin!

**Comment by extr0py** [comment]
> I use c# heavily with Unity, I will see if I can fix this at some point...

Nice 😄 Do you have any games in the app store or anything?

> Also might add on to your plugin, great idea to have it as a plugin!

That would be great!

**Comment by extr0py** [comment]
FYI, since I moved the code to a separate repo, I ported this issue over - extr0py/oni-language-csharp#1. So I'll close this one and track it there.

**Comment by cyansprite** [comment]
> Nice 😄 Do you have any games in the app store or anything?

Not yet currently working on one, got a bit distracted with Oni :P.

**Comment by extr0py** [comment]
@cyansprite , shoot, well keep me posted if you ever need a beta tester 😄

**Comment by extr0py** [comment]
And as an aside, I'm thinking about some ways to gamify Oni - like an improved vimtutor experience / game, as well as just the act of editing and becoming proficient at Vim more enjoyable. #430 tracks some of those ideas - I imagine you might have some ideas around there too, given your background in games!

**Comment by cyansprite** [comment]
> @cyansprite , shoot, well keep me posted if you ever need a beta tester 😄

Do you have an android phone?

> And as an aside, I'm thinking about some ways to gamify Oni - like an improved vimtutor experience / game, as well as just the act of editing and becoming proficient at Vim more enjoyable. #430 tracks some of those ideas - I imagine you might have some ideas around there too, given your background in games!

I was actually thinking about that, like making an adventure game where you move with hjkl and you can use f and t to jump to enemies or something like dta will jump to kill enemy before a, and dfa would jump to kill enemy a... just a thought I never pieced it altogether, I will take a look in a bit :).
