### ISSUE TITLE
Command + v (paste) not working or not implemented?

### ISSUE THREAD

**Issue by josemarluedke** [extr0py/oni#434]
Hey there! Fist, great project, looking forward to it evolve nicely.

I was wondering if command (or ctrl in windows) + v (or c to copy) is implemented or it is just not working for me? I tried to use the edit menu but nothing happens as well. 

Using the last build (v0.2.3-rc2) on MacOs Sierra.

Thanks.

**Comment by bert88sta** [comment]
Check keyboard.tsx, as of right now any command-prefixed keys are just
discarded

**Comment by extr0py** [comment]
Hi @josemarluedke , cheers, thanks for reporting the issue!

Out of the box, Vim / Neovim does not support the standard platform hotkeys for cut/copy/paste (Control/Command + c and Control/Command + v mean different things in Vim).

I've been thinking about how to handle this as part of the goal of "lowering the barrier to entry" to modal editing. I believe that it makes sense to add support for the platform specific hot keys - I'm thinking of the following behavior:

__Visual Mode__
<Control/Command + c> - copy the selected text to the clipboard

__Insert Mode__
<Control/Command + v> - paste the clipboard text

Neovim has clipboard management out of the box, so this potentially be implemented as just `inoremap` and `vnoremap`s in the default config.

**Comment by extr0py** [comment]
The Edit Menu should be using the vim metaphors (yank and paste), but it might not be persisting them on the clipboard.

**Comment by keforbes** [comment]
I have mixed feelings about this.  I can understand wanting to lower the barrier to entry by having the expected key combos for copy/paste, but at the same time, this would get in the way of a Vim-savvy user who wants to use (e.g.) visual block mode.  At the very least, I think this should be configurable.  We should probably define a "beginner mode" and a "true Vim experience" which can be toggled.

**Comment by extr0py** [comment]
Thanks for the feedback, @keforbes, these are great points. I agree, there isn't really a clear answer here.

I guess one option would be to set those mappings when we have the default plugin / Oni behavior active (controlled by the `oni.useDefaultConfig` flag). There is the unfortunate conflict with visual block mode and the usage of <Ctrl+c> in visual mode, but perhaps it is reasonable in terms of lowering the bar if it is documented. I'm leaning towards adding these mappings in the default config but disabled when the `oni.useDefaultConfig` flag is false... I'll keep this around a bit though to stew on it and see if there is any other feedback.

**Comment by cyansprite** [comment]
> Visual Mode
<Control/Command + c> - copy the selected text to the clipboard

I've used c-c to copy in visual mode, as long as you exit visual mode at the same time, it doesn't interfere with my workflow (yes I'm one of those people who use c-c as escape because I learned the `bad` way); As long as you make it direct to "+ and make sure "" stays in tack to what it was originally, it works fine. (I only ever use "+/("* linux only) unless I'm doing something OUT of vim)

> Insert Mode
<Control/Command + v> - paste the clipboard text

I use c-v in insert mode for ""p, as paste from black hole, I would recommend c-s-v from oni's command paletter because you can put in the menu (some people like this), you can use c-s-v which in vim you can not, and because it's what many people are use to from terminal pasting on Linux.

Of course it'll be configurable when we get to that point with keybindings and what we are working on right now, but as far as the `default` I think that would be the easiest.

**Comment by extr0py** [comment]
This should be addressed by #620 , but there are a few remaining issues tracked in #628. I'll close this and use #628 to track the outstanding issues.

**Comment by josemarluedke** [comment]
I have been using this feature for a while now, it works mostly great (just same issue described in #628). Thank you for working on this. 

One thing that I think is missing and it very important for me personally is be able to paste in the command line. I usually have stuff to search in my projects from text coming from the browser or other sources, so I type: `:Ag ` and then I paste it. Currently it does not work. (Ag is my search mechanism). That would be a great addition.

**Comment by extr0py** [comment]
Excellent, thanks for the feedback @josemarluedke !

> One thing that I think is missing and it very important for me personally is be able to paste in the command line.

Ah yes, thanks for sharing the scenario... that makes a lot of sense. I believe this should be pretty straightforward to fix. The special `<C-v>` behavior is gated on being in insert mode, so I think we just need to expand it to happen in command mode as well.

Re-opened just so it wouldn't fall off the radar
