### ISSUE TITLE
Go-langserver

### ISSUE THREAD

**Issue by fasa123** [extr0py/oni#443]
Hi
Could you implement the golang server at https://github.com/sourcegraph/go-langserver/ ?
I for some reason cannot make it run. I copied the Omnisharp extension replaced the references to cs/omnisharp-server to go/go-langserver but it does not work. I open a go file it states Successfully activated but literally nothing happens. No autocomplete, no defs on hover, no linting, nothing.

**Comment by extr0py** [comment]
Thanks for the issue! Broadening the language server support is on the roadmap for the `0.3` release, so this fits into that. I haven't used `go` yet but would be fun to try it out.

Sounds like you've already tried to give a shot - feel free to create a PR and I can help you troubleshoot a bit as well.

**Comment by fasa123** [comment]
https://github.com/fasa123/oni

https://i.imgur.com/vwzIcJX.png

**Comment by extr0py** [comment]
Started making some of the fixes for this in PR #445 . #379 tracks syntax highlighting, and #446 tracks specifying go-langserver path via config.
