### ISSUE TITLE
Text improperly wrapped when opening README.md

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#453]
The `README.md` in the repo is showing some wrapped text:
![image](https://cloud.githubusercontent.com/assets/13532591/26107773/41afecd2-39ff-11e7-9565-342751ce0902.png)

**Comment by keforbes** [comment]
I'm not seeing this behavior.  Has it already been fixed or do you have to do something special to trigger it?

**Comment by extr0py** [comment]
Interesting - it might be specific to the font (using `Fira Code`) or the platform (Windows) since I believe the text rendering is different per-platform. In my case, the width per character gets measured as a fractional value (8.40625px) which might be causing some precision issues.

**Comment by extr0py** [comment]
Fixed by #469
