### ISSUE TITLE
Closing One Instances Closes all

### ISSUE THREAD

**Issue by mrWinston** [extr0py/oni#460]
First of all, Thanks for all the effort. I really like Oni so far! I've just encountered one little Problem:

When i close one instance of Oni with ":q!", all other instances also close. This does not happen, when i terminate an instance with the window managers "x" button. Below is a gif showing the problem: 
![](https://media.giphy.com/media/3o7btYCdCzE83gLNcI/giphy.gif)

I'm running ONI 0.2.3-1235 on KDE Neon (Ubuntu 16.04, 64bit)

**Comment by extr0py** [comment]
Cheers @mrWinston , thanks for the kind words! 

I've run into this issue every so often too, but forgot to log an issue for it - so thanks for opening it up and including the gif. Definitely a bug

**Comment by extr0py** [comment]
Resolved by #461
