### ISSUE TITLE
Jumpy Lists:

### ISSUE THREAD

**Issue by jordwalke** [extr0py/oni#495]
I had some feedback about the autocomplete documentation experience:

![onicomplete](https://user-images.githubusercontent.com/977348/27420596-73732376-56db-11e7-8760-504014a9bc8c.gif)

One thing I noticed, is that it has this particular characteristic that might be suboptimal. That is, when changing the highlighted row in the completion popup, the physical location of *other* items (below it) change. I believe that UIs that don't move elements in lists unless due to scrolling are easier to navigate (unlike accordion style menus), because the user's mental model of where everything is on screen needs to be updated less frequently, or can be updated more quickly.

Scrolling in general doesn't have the same downsides, because all items move in unison - so it only requires that the user understand "every item is where it used to be but moved 10px upwards", which is much more compressed than having to know which items moved upwards, and which moved downwards.

**Comment by jordwalke** [comment]
This could be totally nitpicky.

**Comment by extr0py** [comment]
Not nitpicky at all! This is excellent feedback, thanks for creating the issue!

I was looking at how Atom handles autocompletion, and they have a pretty nice paradigm for this:
![image](https://user-images.githubusercontent.com/13532591/27485702-a1912b6a-57e2-11e7-83dd-89aacd8b2aaa.png)

Atom keep the details pinned on the bottom, and it definitely feels better - and I think you did a great job summarizing exactly _why_. If the UX is done right, the cognitive load on the user should be reduced, and keeping the mental model easy to understand and update is critical.

I think the fix here is to clean up this UI a bit and add the details at the bottom, like Atom does. This should be a relatively simple change .I'm also drafting up a style guide to make sure I continue to refer back to these principles.

There are still rough edges around the UX (the scrolling scenario needs love - #166, flickering is painful - #463, and the typing latency still needs improvements - #229, #90).
