### ISSUE TITLE
Input - Mouse: Add support for scroll wheel

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#5]
From the docs:

For the X11 GUIs (Motif, Athena and GTK) scrolling the wheel generates key
presses <ScrollWheelUp>, <ScrollWheelDown>, <ScrollWheelLeft> and
<ScrollWheelRight>.  For example, if you push the scroll wheel upwards a
<ScrollWheelUp> key press is generated causing the window to scroll upwards
(while the text is actually moving downwards).  The default action for these
keys are:

    <ScrollWheelUp>	    scroll three lines up	*<ScrollWheelUp>*

    <S-ScrollWheelUp>	    scroll one page up		*<S-ScrollWheelUp>*

    <C-ScrollWheelUp>	    scroll one page up		*<C-ScrollWheelUp>*

    <ScrollWheelDown>	    scroll three lines down	*<ScrollWheelDown>*

    <S-ScrollWheelDown>	    scroll one page down	*<S-ScrollWheelDown>*

    <C-ScrollWheelDown>	    scroll one page down	*<C-ScrollWheelDown>*

    <ScrollWheelLeft>	    scroll six columns left	*<ScrollWheelLeft>*

    <S-ScrollWheelLeft>	    scroll one page left	*<S-ScrollWheelLeft>*

    <C-ScrollWheelLeft>	    scroll one page left	*<C-ScrollWheelLeft>*

    <ScrollWheelRight>	    scroll six columns right	*<ScrollWheelRight>*

    <S-ScrollWheelRight>    scroll one page right	*<S-ScrollWheelRight>*

    <C-ScrollWheelRight>    scroll one page right	*<C-ScrollWheelRight>*
This should work in all modes, except when editing the command line.

Looks like it would be easy to add listening to mouse events - just need to coerce the mouse events into the appropriate scroll command

**Comment by bert88sta** [comment]
I'm working on OSX here: I can only get the "scroll" event to fire when pinch zooming. If I disable it in my system preferences, I can't get the event to fire.

**Comment by extr0py** [comment]
@bert88sta - ah ya, might be hard to repro without a mouse wheel!

**Comment by extr0py** [comment]
Thanks for #45 ! Closing this out
