### ISSUE TITLE
Python highlighting bugs.

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#537]
I noticed that "else:" is not highlighted in python. "else :" is.

**Comment by extr0py** [comment]
Interesting, I believe this is controlled by the `python.vim` syntax file included in Neovim / Vim (I don't believe we're doing anything beyond here).

A couple clarifying questions:
- Do you have a file this repros on?
- Does it reproduce in Neovim as well, or only Oni?
- Are you using the `pyls` language server?

**Comment by bert88sta** [comment]
Let me mess around in the bigger python script I have at work. I only noticed it in weird circumstances, might be a syntax thing (ie don't highlight if it's not a grammatically correct else:)

**Comment by extr0py** [comment]
Cool, could be - might worth looking at the `python.vim` or seeing if there is a minimal repro.

It might also be that the language server is giving us `else` as a token to highlight separately, which would cause some weirdness. Let me know if you need any ideas on where to look.

**Comment by bert88sta** [comment]
Haven't seen a repro, so I'm going to go ahead and say that I wrote something poorly and the vim syntax highlighter didn't see it

**Comment by extr0py** [comment]
Cool, thanks for following up and closing it @bert88sta ! Nice to see the issue count go down a bit..
