### ISSUE TITLE
Latest Oni crashes on OSX

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#538]
I mucked up my old git, so I deleted and reforked. I did all the rebuilding, and I get this:

![screen shot 2017-07-13 at 10 02 01 pm](https://user-images.githubusercontent.com/8421641/28195210-f01a8256-6816-11e7-8e00-1a7e69102a45.png)

**Comment by bert88sta** [comment]
As a sanity check I npm rm'd everything, but rebuilding isn't working.

**Comment by keforbes** [comment]
Do you need to run `npm link` again?

**Comment by bert88sta** [comment]
I swear every time I reinstall I break it and look like an idiot :P

**Comment by extr0py** [comment]
Glad you got it working! A few of the dependencies have updated, so you might need to kill all existing Oni instances, clear your `node_modules` folder, and re-run `npm install`.
