### ISSUE TITLE
Performance: Use async calls for getTrackedFiles / getUntracked files

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#549]
In the QuickOpen experience (Ctrl+P), there is a clear bottleneck with the synchronous git spawning:
![image](https://user-images.githubusercontent.com/13532591/28493326-b5285f88-6ec9-11e7-8ea7-f59e7037d3c5.png)

**Comment by cyansprite** [comment]
I am looking into this

**Comment by extr0py** [comment]
Awesome, thanks @cyansprite ! I hit this a bunch in my workflow

**Comment by cyansprite** [comment]
Yeah same and it overrided my old way of doing it and I think this is my favorite line of feature so glad to be working on it :)

**Comment by extr0py** [comment]
> Yeah same and it overrided my old way of doing it and I think this is my favorite line of feature so glad to be working on it :)

Nice, that's great to hear 😄

**Comment by cyansprite** [comment]
Pretty much done with this... just making some minor changes then I will push my commit to my PR and then you can let me know what you think.

**Comment by extr0py** [comment]
Cool, I just checked the PR and I like how you consolidate the two calls.

**Comment by extr0py** [comment]
Looks like this was addressed by #574 , closing.
