### ISSUE TITLE
Lightweight?

### ISSUE THREAD

**Issue by zQueal** [extr0py/oni#559]
I really feel this classification is a huge misnomer.

Starting up Oni, with nothing opened it's consuming 90MB of RAM and 2% CPU just being idle. Not to mention the install folder is 250MB large. The binary alone is 56MB.

gVim running by itself consumes less than 10MB of RAM and is just under 3MB for me.

What exactly about Oni is lightweight?

**Comment by extr0py** [comment]
That's fair criticism - with the phrase `Lightweight IDE`, I was considering it relative to Visual Studio or Webstorm. But I can see where someone coming from gvim wouldn't see that way.

And I agree with your concerns. I thought I had some of these issues tracked, but I opened up #560 (relating to the installation package size / footprint) & #561 (CPU usage when idle).

Lightweight might be a poor choice of words, considering how small `gvim.exe` and `nvim-qt` are, in comparison. But it is certainly a goal for Oni to be ligher than it is today.

For now, I updated the tagline at the top of the project to read  "An IDE built around Neovim".

**Comment by zQueal** [comment]
> But it is certainly a goal for Oni to be ligher than it is today.

Sounds good to me! Great work, by the way. I didn't necessarily mean to criticize, just was wondering what the mentality was there.

**Comment by extr0py** [comment]
> Sounds good to me! Great work, by the way.

Cheers, thanks! 😄 

> I didn't necessarily mean to criticize, just was wondering what the mentality was there.

For sure, it's a valid point. Setting the right expectations is important - thanks for logging the issue!
