### ISSUE TITLE
I've lost the ability to resize on OSX

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#565]
I ran: 

npm install; npm run build; npm link

after merging the new tabline implementation. My (full) screen looks kind of ridiculous and blown up

![screen shot 2017-08-04 at 4 05 25 pm](https://user-images.githubusercontent.com/8421641/28985058-ccf1a088-792e-11e7-900b-054fe026c0c3.png)

**Comment by bert88sta** [comment]
I still seriously think that somehow TMUX is messing this up

**Comment by bert88sta** [comment]
Ah nevermind, fixed it. I'm really not sure why weird things like this happen. Through my own testing, it seems like it's either the issue with OSX not really closing the last process, or TMUX is messing with things (which has been the case with other programs that run from command line)

**Comment by extr0py** [comment]
Oh, interesting! There was a change to the `main` process which gets shared between instances - so you might need to close all instances of Oni for the resize to work correctly. It now uses this thing called a `ResizeObserver` that requires a flag to be specified on the browser, which happens in the main process:
__main.js__
```
...
    const webPreferences = {
        blinkFeatures: "ResizeObserver",
    }
...
```

 If there was an instance  of Oni opened, it wouldn't get that flag, and resize wouldn't be hooked up.

I use `killall Electron` in OSX to clean between builds. Let me know if you still hit it after running that.
