### ISSUE TITLE
FocusGained vim event doesn't work

### ISSUE THREAD

**Issue by hoschi** [extr0py/oni#575]
I use [vim-gitgutter]( https://github.com/airblade/vim-gitgutter) and also have this code to switch to normal line numbers when window looses focus:
```VimL
" Use relativenumber only in the focused window
if exists('&relativenumber')
  set relativenumber
  augroup WindowRNU
    auto!
    auto BufWinEnter,WinEnter,FocusGained * setlocal relativenumber
    auto WinLeave,FocusLost               * setlocal nornu
  augroup END
endif
```

Both don't work with Oni, because `FocusGained` and `FocusLost` doesn't fire.

**Comment by hoschi** [comment]
that was fast 0.0 thanks!

**Comment by extr0py** [comment]
@hoschi , thanks 😄 That one was relatively straightforward and had been on my backlog anyway.... so figured it was time to go in. Appreciate you logging the issue!
