### ISSUE TITLE
How to modify cursor?

### ISSUE THREAD

**Issue by hoschi** [extr0py/oni#578]
I want to change the cursor color to something other than "black", because with a light theme the text color is black(ish) and so ... black on black is hard to read ;)
I thought this can be done with:
```VimL
hi Cursor guifg=#ffffff guibg=#ffffff guisp=#ffffff gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
```
but doesn't work. Also it doesn't work in terminal, but I think because cursor color is controlled by terminal settings here.

Also I want to disable the blinking which should be done by setting:
```VimL
" Disable all blinking:
:set guicursor+=a:blinkon0
```
taken from http://vim.wikia.com/wiki/Configuring_the_cursor
Which also doesn't work :(

**Comment by cyansprite** [comment]
I know neovim is having issues with the cursor color is well... in the terminal if you
```vim
set termguicolors
```
does it work?

**Comment by cyansprite** [comment]
if your terminal such as terminator controls the cursor color try gnome or tilix

**Comment by hoschi** [comment]
I'm fine with the color in terminal, just wanted to mention that.

**Comment by extr0py** [comment]
Ya, right now, the cursor in Oni is implemented completely outside of Neovim (aside from the positioning information).

__Long-term__ my goal is to enable _skins_ / _styling_ - like customization beyond just colorschemes. In other words, I'd like enough customization here to enable something like [atom power mode](https://atom.io/packages/activate-power-mode) for Oni.

I could see customization easily happening via CSS, by exposing a set of canonical styles on the cursor element.

There are a few discussions around this:
- CSS Theming: #412 
- Colorscheme synchronization: #33 

In the meantime, though, we should be respecting the colors and state Neovim gives us for the cursor. The defaults are unusable on a light colorscheme, unfortunately.

**Comment by extr0py** [comment]
It's actually pretty straightforward in this case to pick more reasonable colors for the cursor, since we stash the current foreground / background color as part of screen rendering.

Using those gives me this for `solarized8_light`:
![image](https://user-images.githubusercontent.com/13532591/29081704-179221e4-7c18-11e7-9db2-872b7f5500a0.png)

Putting together a PR now.
