### ISSUE TITLE
set mouse=a as default?

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#580]
This is an IDE. It has a GUI. People's individual configs can undo if they'd wish, but neovim already has fairly smart handling of multiple clicks and visual selection with drag (which works with Oni without any further additions to Mouse.ts)

**Comment by cyansprite** [comment]
:+1: 
I would also like a way to select text that isn't selectable my neovim's mouse=a such as an error msg so I can copy and paste it outside of the editor, but as far as defaults go I think this is very reasonable.

**Comment by extr0py** [comment]
Good catch, makes sense to me!
