### ISSUE TITLE
Tabs being opened in window splits (?)

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#593]
[![https://gyazo.com/03dba385abddd98b0741d47acdb079dc](https://i.gyazo.com/03dba385abddd98b0741d47acdb079dc.gif)](https://gyazo.com/03dba385abddd98b0741d47acdb079dc)

Tabs are supposed to contain window splits of their own, but these seem to open whatever buffer is first in a tabpage into the current split (which works perfectly fine if you don't work with split windows at all)

**Comment by extr0py** [comment]
By default, the tabline shows opened buffers. If you want it to show vim-style-tabs, you'll need to set the `tabs.showVimTabs` option to true. There's some discussion around this in #586 too.

**Comment by bert88sta** [comment]
Hmm, not sure I like it as a default setting or as a gui-friendly setting, although I could imagine it being useful if i wanted persistent windows.

**Comment by extr0py** [comment]
> Hmm, not sure I like it as a default setting or as a gui-friendly setting

IMO, showing buffers by default at the top more closely maps to how other _most other editor works_ - and one of the goals of Oni is to lower the barrier to entry. 'Tabs' in the vim world mean something different from all other editors that have this UX concept. If someone prefers the 'vim-tab' based workflow, they can still enable that.

I'll close this for now, but let me know if you have any other thoughts.
