### ISSUE TITLE
Scrollbar is gone

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#596]
Is it just me?  Is it just Linux?  I don't have a scrollbar in Oni anymore.

![no_scrollbar](https://user-images.githubusercontent.com/817509/29221877-9e3384f6-7e7d-11e7-8d46-bc54490df157.png)

**Comment by CrossR** [comment]
Same for me on Windows 10, using the latest commit on master.

**Comment by extr0py** [comment]
Ah yes, this is a regression from some of the react / redux performance work. I have a fix for this, I'll push it up. Sorry about that!

**Comment by extr0py** [comment]
Fixed by #599
