### ISSUE TITLE
Scroll improvements.

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#61]
First, the scroll bar jitters from left to right

https://gyazo.com/e886941e230b901f7bb06fd8209d0651

Second, I've tried implementing some math to determine if the scroll is in a different buffer, but it gets laggy. Basically in Mouse.ts I just created variables for the last cell that the mouse event registered to, and then I compared them. Is there a better way to implement this? I like being able to scroll without clicking, but it's not going to be a dealbreaker

**Comment by extr0py** [comment]
> First, the scroll bar jitters from left to right

Unfortunately there's some bugs in `OverlayManager.ts` in terms of how the window position is calculated. Sometimes, it gets off a bit. I think we could use some of the API members in the `msgpack-rpc` API to get the open windows - there's methods to get all the windows, and then their position and size - that would be a much more reliable way than the current strategy. It actually impacts everything that is an _overlay_ - you can even see it in the last animated gif in the readme for live evaluation :( As well as the error messages.

We can also always get the currentBuffer / currentWindow from those same msgpack-rpc APIs (They live in `_neovim` on NeovimInstance - there aren't good typings for it, but you can see some of the members in the debugger -> `window.neovim._neovim` gives some details). Fixing the OverlayManager to give more reliable window dimensions will help across the board, and I anticipate several other pieces of functionality being built on top of it later too (overlaying git blame / git changes, etc)

**Comment by extr0py** [comment]
Regarding needing the current buffer for scrolling without clicking - I think if you just send the scroll commands as input, it should 'just work' as Neovim will apply those to the currently active buffer. Does that not work?

**Comment by bert88sta** [comment]
@extr0py for some reason I removed the coords from the emit, just went and fixed it. Is there anything else you want done it Mouse before a PR comes your way?

**Comment by extr0py** [comment]
@bert88sta -Hmm, I don't think there is any more mouse functionality I had in mind in the short-term. Eventually for some of the enhanced UI components like auto-complete, quick-open, etc it might be helpful to add some click handling, but not really needed for now and it's separate from Mouse.ts - that would be handled in the components.

**Comment by extr0py** [comment]
Jitteriness is fixed by #75 - if there any issues we want to track, feel free to log them as separate items!
