### ISSUE TITLE
Tabline says dirty after undolevels = 0

### ISSUE THREAD

**Issue by cyansprite** [extr0py/oni#624]
Vim help:
```When all changes have been undone, the buffer is not considered to be changed.
It is then possible to exit Vim with ":q" instead of ":q!".
Note that this is relative to the last write of the file.  Typing "u" after
":w" actually changes the buffer, compared to what was written, so the buffer
is considered changed then.
```

So you can change the buffer, but the tab icon is still dirty.
I'm not sure what we need to detect in order to update the tab state, I can do some research on this.

**Comment by extr0py** [comment]
Nice catch... I've seen a bit of flakiness around the dirty indicator so perhaps this is related.

I think right now we are using the 'b:changedtick' variable - perhaps we need to switch to use '&modified'?

**Comment by cyansprite** [comment]
right because b:changedtick will change even if you type and then undo like wise undo redo (assuming you saved after a change)

so checking &modified <i>should</i> give us the correct answer each time, I just test and it and seems correct

**Comment by cyansprite** [comment]
```
b:changedtick	The total number of changes to the current buffer.  It is
		incremented for each change.  An undo command is also a change
		in this case.  This can be used to perform an action only when
		the buffer has changed. 
```

**Comment by extr0py** [comment]
> so checking &modified should give us the correct answer each time, I just tested it and it and seems correct

Cool, that does seem what we want! 

To implement this, right now, the `UI.Actions.bufferUpdate` takes a `version` parameter. Seems like we'd want to replace that with an `isDirty` flag. We'd have to modify it in a couple places (action creator, action, reducer, state).

In addition, we don't send up the `&modified` flag. We might want to add that to the context we send up from neovim -> Oni. If we have that, then we can pass that easily to the `bufferUpdate` redux action.

**Comment by extr0py** [comment]
Just tried out the latest changes - works great! The behavior of the dirty flag is working as I'd expect it now 😄 Thanks!

**Comment by extr0py** [comment]
Since this is closed now, @cyansprite , you should be able to submit the solution @ bountysource. https://www.bountysource.com/issues/48329508-tabline-says-dirty-after-undolevels-0
