### ISSUE TITLE
<S-CR> keybinding isn't working

### ISSUE THREAD

**Issue by volny** [extr0py/oni#642]
I use shift-enter instead of enter to insert a new line.  
`inoremap <S-CR> <NL>` is ignored and not working. As a sidenote `inoremap <C-CR> <NL>` works as expected.

**Comment by extr0py** [comment]
Thanks for isolating and logging the issue, @volny ! I'm able to reproduce this. It's interesting that <C-CR> works - I wonder if we aren't mapping the shift case correctly here in `Keyboard.ts`.

**Comment by justjoeyuk** [comment]
@volny Should be fixed in the referenced PR 😄

**Comment by justjoeyuk** [comment]
@volny The latest PR should solve the problem :smile:

**Comment by keforbes** [comment]
Fixed by #652.
