### ISSUE TITLE
Message UI: Add confirmation when add path / remove path succeeeds

### ISSUE THREAD

**Issue by extr0py** [extr0py/oni#653]
After #646, which adds the 'Add to path' and 'Remove to path' tasks on OSX, it'd be helpful to have some sort of confirmation for the user - to let them know that the operation was completed successfully.

This would be a good case for a message / notification UI. There is a `Messages.tsx` that was started, but it's still pretty rough, and not completely hooked up via redux yet.

**Comment by justjoeyuk** [comment]
This is kind of implemented in #646 in the sense that tasks can now have messages for success/fail. We still need to be able to implement a success/fail callback but that's a different task.

**Comment by extr0py** [comment]
Thanks @justjoeyuk ! Ya, looks like that is addressed, it's really helpful to have that feedback. I'll go ahead and close this out.
