### ISSUE TITLE
AutoCompletion use `Tab` key instead of `Enter` key to 

### ISSUE THREAD

**Issue by fanchangyong** [extr0py/oni#654]
I love this project, but how can I config to use `Tab` key instead of `Enter` key to select a auto completion item?
thanks!

**Comment by cyansprite** [comment]
It's a work in progrsss for keybindings we are fixing atm. Look at the PR by @extr0py

If you want you can manually add it with a custom build of your own while we hash it out.

**Comment by extr0py** [comment]
Yes, working on #633, I'm hoping to get this in by end of week. I know it is a huge pain point right now with Oni!

**Comment by extr0py** [comment]
#633 is now in, and this is added as a default key binding (both `<tab>` and `<enter>` complete now). For further customization, check out:  https://github.com/extr0py/oni/wiki/Configuration#keyboard-bindings
