### ISSUE TITLE
Fuzzy Finding stalls when opening Oni from the dock (Mac OS)

### ISSUE THREAD

**Issue by someguynamedmatt** [extr0py/oni#662]
Reading through the docks I know Oni's fuzzy finder searches a directory using `git ls-files` and "falls back to other methods" when a git directory is not found. I'm not sure what mechanism this is, but in Mac OS (Sierra: 10.12.5) the fuzzy finder never stops loading after I've opened it from my dock:

![screen shot 2017-08-25 at 10 46 40 am](https://user-images.githubusercontent.com/17413539/29725979-d9be1fb2-8982-11e7-8fb4-6cda4f7d0070.png)

Using the `v0.2.8` release of Oni

**Comment by jaywcjlove** [comment]
@someguynamedmatt  Select a folder. 


![image](https://user-images.githubusercontent.com/1680273/29726080-03b90e0c-8a01-11e7-8edc-712d1f6f0fe2.png)

**Comment by someguynamedmatt** [comment]
@jaywcjlove Awesome. Thanks. I'd like to help with the project. Can you (or anyone else) point me to where the file system is being scanned when the user checks the fuzzy finder?

**Comment by keforbes** [comment]
> I'd like to help with the project. Can you (or anyone else) point me to where the file system is being scanned when the user checks the fuzzy finder?

Check `browser/src/Services/QuickOpen.ts`

**Comment by keforbes** [comment]
Also, check https://github.com/extr0py/oni/pull/574 for a discussion on the feature since @cyansprite basically re-wrote the entire feature recently.

**Comment by someguynamedmatt** [comment]
Thanks, @keforbes

**Comment by cyansprite** [comment]
Fixing the slow sync strategy with PR #635 
Plus a few more things, you can try pulling the fork and branch to see if it helps.

May I ask what dir it opens when you open it from dock? We should fall back to the bookmark/open folder strategy if you are in install or home dir.

**Comment by someguynamedmatt** [comment]
@cyansprite I used the "Download for Mac" link that's present on the README. When I open it from the dock it's showing the root directory `/` in the lower-left corner. I'm using the latest release `0.2.8`.

**Comment by cyansprite** [comment]
Root dir huh... I will add a case for that thankb you. 
I'm going to make a robust way of this never happening even with the new method. ( filtering can still be laggy with a large list)

Thanks for the reply!!

**Comment by someguynamedmatt** [comment]
@cyansprite No problem. Thanks for the work. I wanna tear through the source and issues and try to contribute when I can.

**Comment by extr0py** [comment]
Awesome! I think it's pretty common to hit that 'root dir' case on first install / open of Oni. Ideally that 'happy path' scenario should be smooth and at least point the user to the 'Open Folder' and 'Bookmarks' options.

> Also was it the latest release or did you build from source? Idk if it's in the latest release that's a question for@extr0py

Looks like the bookmark work did make it into the 0.2.8 release, but perhaps the root-dir case isn't handled? Sounds like from the discussion we'll have to include that in our special cases for now (root dir, install directory, home directory)

> I wanna tear through the source and issues and try to contribute when I can.

Excellent 😄
