### ISSUE TITLE
Cursor in visual mode is | (should be █)

### ISSUE THREAD

**Issue by skosch** [extr0py/oni#665]
New oni user here – I hope this is a legitimate issue and not due to my configuration. When I select text in (n)vim, the cursor stays in normal mode (i.e. `█`); when I select text in oni, the cursor becomes `|`. Is this intended behaviour?

**Comment by TalAmuyal** [comment]
Same behavior for me.
I think it should stay `█` in visual mode as well as `|` is very confusing...

**Comment by extr0py** [comment]
Yes, good catch, thanks for logging the issue @skosch ! This is a bug, should be in parity with vim.

**Comment by extr0py** [comment]
This is a pretty simple fix, the logic was just busted for picking the cursor shape. One thing I've thought might be nice is to have a subtle differentiation for the cursor between visual and normal modes (like a subtle border), but that can come later.
