### ISSUE TITLE
Control flow for Oni in vimrc

### ISSUE THREAD

**Issue by robertocarta** [extr0py/oni#666]
Hi, is there a way to put if statements in the vimrc to tell check if it's being loaded by oni?
Sort of what we do with
`if has('nvim')`

BTW This project is absolutely amazing.

**Comment by extr0py** [comment]
> BTW This project is absolutely amazing.

Cheers, thanks for trying it out 😄 

Eventually, I'd like to have a custom build of Neovim for oni (which would mean we could do something like `if has('oni')`).

Right now, the `g:gui_oni` value is set on load, so you can use `if exists("g:gui_oni")` in your vimrc to handle config specific to oni.

Hope that helps! I'll close this for now, but please feel free to reopen if that doesn't work for you.
