### ISSUE TITLE
Save As Not working

### ISSUE THREAD

**Issue by CrossR** [extr0py/oni#683]
When you run "Save As" from the Menu, it doesn't actually save to the correct location. 

It looks to be a path normalisation issue, as saving to "F:\User Files\Desktop\Test.txt" actually becomes "F:User FilesDesktopTest.txt".

If the paths didn't give it away, this is on Windows, so I'm not sure if other platforms are affected.

I'll have a look into it, since hopefully its a tiny fix.

**Comment by CrossR** [comment]
Yeah, looks like changing `name` to `normalizePath(name)` fixed this for me, so I'll make a PR.

**Comment by extr0py** [comment]
> Yeah, looks like changing name to normalizePath(name) fixed this for me, so I'll make a PR.

Awesome! Thanks for fixing it 😄

**Comment by CrossR** [comment]
Fixed with #684.
