### ISSUE TITLE
Blank white screen on load

### ISSUE THREAD

**Issue by mdxprograms** [extr0py/oni#72]
I'm getting a blank screen when running `oni` after installation.

My current OS is `10.12.2 Beta (16C53a)`
I'm running node version `7.2`

Is there a specific version this is supported for node wise?

**Comment by extr0py** [comment]
Hmm, did you install via `npm install -g oni-vim` or by cloning and building? 

Node 7.2 should be fine - could be related to #22 as well.

Thanks for trying it out!

**Comment by mdxprograms** [comment]
I should also note after opening developer tools, the console is outputting
```Failed to load resource .nvm/versions/node/v7.2.0/lib/node_modules/oni-vim/dist/browser/bundle.js```

**Comment by mdxprograms** [comment]
Correct. I ran `npm install -g oni-vim`

**Comment by extr0py** [comment]
Looks like the package is busted - some of the built files were .gitignored. I'll publish an updated package

**Comment by mdxprograms** [comment]
Excellent! Thank you so much! Look forward to messing with it 👍

**Comment by extr0py** [comment]
Published 0.1.3, and verified the built files are included. Hope it works better now!

**Comment by mdxprograms** [comment]
it's up and running now! thanks again
