### ISSUE TITLE
Error when in a different workspace/desktop

### ISSUE THREAD

**Issue by bert88sta** [extr0py/oni#77]
On mac, you have multiple "desktops" to work on, think like workspaces in linux. Basically, if I'm one that does not have oni open and I click on it in the dock, I get this.

![screen shot 2016-12-10 at 2 34 40 pm](https://cloud.githubusercontent.com/assets/8421641/21075679/0abc100a-bee6-11e6-9d7a-9a8d6e96aed2.png)

**Comment by bert88sta** [comment]
It doesn't break the app at all, just a slight tick.

**Comment by extr0py** [comment]
Interesting, guess I never hit this case since I'm usually on Windows. I think I know how to fix it though
