### ISSUE TITLE
Document current keyboard shortcuts

### ISSUE THREAD

**Issue by keforbes** [extr0py/oni#92]
The main project page has images showing fuzzy finder, quick info, code completion, and line evaluation working in Oni.  Please document the keyboard shortcuts for activating these features.

**Comment by extr0py** [comment]
Great point, I just sort of through those up there and if people don't know where to look or where the support lives... they are probably pretty disappointed when they open the app :) I'll start calling them out in the docs shortly

**Comment by extr0py** [comment]
We have most of the keyboard shortcuts documented now, and are in the process of moving some of our documentation to the gitbook / wiki.
